// Generated by tools/generate_alqadim_atlas.py from the original game data.
window.ALQADIM_ATLAS_DATA = {
  "format": "Al-Qadim Cyberlore world atlas v7",
  "rendering": "Terrain, cached-origin runtime scenery, optional roof/foreground layer, NPC spawn metadata, and original 256-colour palette",
  "worldCount": 31,
  "worlds": [
    {
      "id": "acid",
      "engineId": "ACID",
      "title": "Acid Dungeon",
      "image": "images/alqadim-atlas/acid.png",
      "roofImage": "images/alqadim-atlas/acid-roofed.png",
      "width": 2048,
      "height": 2048,
      "mapWidth": 128,
      "mapHeight": 128,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 263,
      "annotationKey": "map_acid_dungeon.png",
      "manualImage": "images/alqadim/map_acid_dungeon.png",
      "sourceFile": "WORLDS/ACID.LIB",
      "sourceBytes": 277172,
      "sourceSha256": "ba63f0fa6eb18241c1b46741724bd6deb23544ee1271c01421ab150761661179",
      "sceneryCount": 250,
      "foregroundCount": 14,
      "actorCount": 92,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell *",
          "x": 950,
          "y": 1606,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "acida",
      "engineId": "ACIDA",
      "title": "Acid Dungeon \u2014 inner chamber",
      "image": "images/alqadim-atlas/acida.png",
      "roofImage": "images/alqadim-atlas/acida-roofed.png",
      "width": 752,
      "height": 1072,
      "mapWidth": 47,
      "mapHeight": 67,
      "tileSize": 16,
      "tileBits": 7,
      "tileCount": 76,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/ACIDA.LIB",
      "sourceBytes": 64102,
      "sourceSha256": "2d4ba8bc6c5b324783a3a090facf4f1a21bc0300d9d18183a011f8267077d17d",
      "sceneryCount": 56,
      "foregroundCount": 3,
      "actorCount": 13,
      "namedActors": [
        {
          "id": 8,
          "name": "your name ell",
          "x": 585,
          "y": 715,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 136,
          "name": "Bird",
          "x": 274,
          "y": 826,
          "spriteId": 10,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "alkatrz",
      "engineId": "ALKATRZ",
      "title": "Alkatraz",
      "image": "images/alqadim-atlas/alkatrz.png",
      "roofImage": null,
      "width": 2016,
      "height": 1920,
      "mapWidth": 126,
      "mapHeight": 120,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 142,
      "annotationKey": "map_dungeon_alkatraz.png",
      "manualImage": "images/alqadim/map_dungeon_alkatraz.png",
      "sourceFile": "WORLDS/ALKATRZ.LIB",
      "sourceBytes": 458669,
      "sourceSha256": "c081517cb90a3f78f1f92184c5b2c39a7b8e4a774a1ff71007dca6635c72557e",
      "sceneryCount": 179,
      "foregroundCount": 0,
      "actorCount": 101,
      "namedActors": [
        {
          "id": 343,
          "name": "guardian ammut",
          "x": 202,
          "y": 83,
          "spriteId": 237,
          "positionKind": "authored-spawn"
        },
        {
          "id": 383,
          "name": "your_brother",
          "x": 1636,
          "y": 207,
          "spriteId": 76,
          "positionKind": "authored-spawn"
        },
        {
          "id": 266,
          "name": "Alk_guard12",
          "x": 1339,
          "y": 326,
          "spriteId": 352,
          "positionKind": "authored-spawn"
        },
        {
          "id": 265,
          "name": "Merc_leader",
          "x": 1153,
          "y": 333,
          "spriteId": 282,
          "positionKind": "authored-spawn"
        },
        {
          "id": 350,
          "name": "Al_mummy",
          "x": 213,
          "y": 366,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        },
        {
          "id": 348,
          "name": "Al_mummy",
          "x": 93,
          "y": 368,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        },
        {
          "id": 263,
          "name": "Alk_guard14",
          "x": 1117,
          "y": 390,
          "spriteId": 374,
          "positionKind": "authored-spawn"
        },
        {
          "id": 323,
          "name": "Alk_guard15",
          "x": 1189,
          "y": 391,
          "spriteId": 374,
          "positionKind": "authored-spawn"
        },
        {
          "id": 264,
          "name": "Alk_guard13",
          "x": 1340,
          "y": 393,
          "spriteId": 352,
          "positionKind": "authored-spawn"
        },
        {
          "id": 347,
          "name": "Al_mummy",
          "x": 60,
          "y": 402,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 351,
          "name": "Al_mummy",
          "x": 253,
          "y": 405,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        },
        {
          "id": 352,
          "name": "Al_mummy",
          "x": 143,
          "y": 421,
          "spriteId": 6,
          "positionKind": "authored-spawn"
        },
        {
          "id": 268,
          "name": "Alk_mage",
          "x": 1040,
          "y": 743,
          "spriteId": 389,
          "positionKind": "authored-spawn"
        },
        {
          "id": 176,
          "name": "Al_spiders",
          "x": 401,
          "y": 786,
          "spriteId": 418,
          "positionKind": "authored-spawn"
        },
        {
          "id": 258,
          "name": "Alk_guard10",
          "x": 1324,
          "y": 791,
          "spriteId": 352,
          "positionKind": "authored-spawn"
        },
        {
          "id": 259,
          "name": "Alk_guard11",
          "x": 1327,
          "y": 859,
          "spriteId": 352,
          "positionKind": "authored-spawn"
        },
        {
          "id": 141,
          "name": "Al_spiders",
          "x": 402,
          "y": 866,
          "spriteId": 418,
          "positionKind": "authored-spawn"
        },
        {
          "id": 150,
          "name": "Al_mummy",
          "x": 296,
          "y": 901,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        },
        {
          "id": 235,
          "name": "Al_mummy",
          "x": 231,
          "y": 928,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        },
        {
          "id": 257,
          "name": "Alk_guard8",
          "x": 861,
          "y": 984,
          "spriteId": 331,
          "positionKind": "authored-spawn"
        },
        {
          "id": 236,
          "name": "Al_mummy",
          "x": 258,
          "y": 990,
          "spriteId": 6,
          "positionKind": "authored-spawn"
        },
        {
          "id": 152,
          "name": "Al_spiders",
          "x": 419,
          "y": 990,
          "spriteId": 418,
          "positionKind": "authored-spawn"
        },
        {
          "id": 254,
          "name": "Alk_guard9",
          "x": 824,
          "y": 1003,
          "spriteId": 332,
          "positionKind": "authored-spawn"
        },
        {
          "id": 143,
          "name": "Al_spiders",
          "x": 422,
          "y": 1118,
          "spriteId": 418,
          "positionKind": "authored-spawn"
        },
        {
          "id": 205,
          "name": "Alk_guard7",
          "x": 1053,
          "y": 1240,
          "spriteId": 331,
          "positionKind": "authored-spawn"
        },
        {
          "id": 198,
          "name": "Alk_guard6",
          "x": 908,
          "y": 1278,
          "spriteId": 331,
          "positionKind": "authored-spawn"
        },
        {
          "id": 319,
          "name": "Alk_guard5",
          "x": 992,
          "y": 1327,
          "spriteId": 330,
          "positionKind": "authored-spawn"
        },
        {
          "id": 159,
          "name": "Al_ammut",
          "x": 307,
          "y": 1349,
          "spriteId": 233,
          "positionKind": "authored-spawn"
        },
        {
          "id": 243,
          "name": "Al_ammut",
          "x": 372,
          "y": 1414,
          "spriteId": 229,
          "positionKind": "authored-spawn"
        },
        {
          "id": 126,
          "name": "Alk_guard3",
          "x": 903,
          "y": 1418,
          "spriteId": 332,
          "positionKind": "authored-spawn"
        },
        {
          "id": 315,
          "name": "Alk_guard2",
          "x": 873,
          "y": 1496,
          "spriteId": 332,
          "positionKind": "authored-spawn"
        },
        {
          "id": 318,
          "name": "Alk_guard4",
          "x": 1188,
          "y": 1504,
          "spriteId": 331,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell F",
          "x": 1816,
          "y": 1524,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 122,
          "name": "Alk_guard1",
          "x": 1388,
          "y": 1711,
          "spriteId": 330,
          "positionKind": "authored-spawn"
        },
        {
          "id": 133,
          "name": "Alk_ettin",
          "x": 556,
          "y": 1728,
          "spriteId": 304,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "dedhold",
      "engineId": "DEDHOLD",
      "title": "Ships' Hold",
      "image": "images/alqadim-atlas/dedhold.png",
      "roofImage": "images/alqadim-atlas/dedhold-roofed.png",
      "width": 320,
      "height": 512,
      "mapWidth": 20,
      "mapHeight": 32,
      "tileSize": 16,
      "tileBits": 7,
      "tileCount": 68,
      "annotationKey": "map_ships_hold.png",
      "manualImage": "images/alqadim/map_ships_hold.png",
      "sourceFile": "WORLDS/DEDHOLD.LIB",
      "sourceBytes": 55938,
      "sourceSha256": "4232d8c80e83fe0742fd956f6bf4f91491bedf581f4e9649c33a18e1306538aa",
      "sceneryCount": 16,
      "foregroundCount": 3,
      "actorCount": 5,
      "namedActors": [
        {
          "id": 96,
          "name": "Zombie",
          "x": 128,
          "y": 259,
          "spriteId": 13,
          "positionKind": "authored-spawn"
        },
        {
          "id": 71,
          "name": "Zombie",
          "x": 216,
          "y": 259,
          "spriteId": 13,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Bert Mitchell ]",
          "x": 168,
          "y": 480,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "feud",
      "engineId": "FEUD",
      "title": "Caliph's Palace \u2014 feud state",
      "image": "images/alqadim-atlas/feud.png",
      "roofImage": "images/alqadim-atlas/feud-roofed.png",
      "width": 2048,
      "height": 1280,
      "mapWidth": 128,
      "mapHeight": 80,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 322,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/FEUD.LIB",
      "sourceBytes": 280750,
      "sourceSha256": "206c202043100b29e302c9b7a455de98ab3c183023bbed67fa54be96404a22e9",
      "sceneryCount": 301,
      "foregroundCount": 9,
      "actorCount": 39,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell F",
          "x": 1007,
          "y": 232,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 249,
          "name": "Gan1",
          "x": 634,
          "y": 445,
          "spriteId": 92,
          "positionKind": "authored-spawn"
        },
        {
          "id": 271,
          "name": "Raz1",
          "x": 1592,
          "y": 540,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 388,
          "name": "Gan1",
          "x": 607,
          "y": 541,
          "spriteId": 91,
          "positionKind": "authored-spawn"
        },
        {
          "id": 320,
          "name": "Raz1",
          "x": 1562,
          "y": 607,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 88,
          "name": "Feud_well",
          "x": 896,
          "y": 671,
          "spriteId": 9,
          "positionKind": "authored-spawn"
        },
        {
          "id": 403,
          "name": "Gan2",
          "x": 509,
          "y": 739,
          "spriteId": 92,
          "positionKind": "authored-spawn"
        },
        {
          "id": 411,
          "name": "Gan2",
          "x": 570,
          "y": 740,
          "spriteId": 92,
          "positionKind": "authored-spawn"
        },
        {
          "id": 407,
          "name": "Your_brother",
          "x": 899,
          "y": 740,
          "spriteId": 24,
          "positionKind": "authored-spawn"
        },
        {
          "id": 318,
          "name": "Raz2",
          "x": 1416,
          "y": 780,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 261,
          "name": "Gan2",
          "x": 512,
          "y": 794,
          "spriteId": 91,
          "positionKind": "authored-spawn"
        },
        {
          "id": 218,
          "name": "Raz2",
          "x": 1448,
          "y": 800,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 389,
          "name": "Raz2",
          "x": 1475,
          "y": 831,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 362,
          "name": "Gan3",
          "x": 276,
          "y": 885,
          "spriteId": 90,
          "positionKind": "authored-spawn"
        },
        {
          "id": 356,
          "name": "Ganleader",
          "x": 398,
          "y": 933,
          "spriteId": 113,
          "positionKind": "authored-spawn"
        },
        {
          "id": 468,
          "name": "Gan3",
          "x": 521,
          "y": 948,
          "spriteId": 91,
          "positionKind": "authored-spawn"
        },
        {
          "id": 469,
          "name": "Gan3",
          "x": 376,
          "y": 977,
          "spriteId": 91,
          "positionKind": "authored-spawn"
        },
        {
          "id": 466,
          "name": "Raz3",
          "x": 1823,
          "y": 988,
          "spriteId": 71,
          "positionKind": "authored-spawn"
        },
        {
          "id": 465,
          "name": "Raz3",
          "x": 1711,
          "y": 1003,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 357,
          "name": "Gan3",
          "x": 403,
          "y": 1011,
          "spriteId": 90,
          "positionKind": "authored-spawn"
        },
        {
          "id": 307,
          "name": "Razleader",
          "x": 1753,
          "y": 1018,
          "spriteId": 159,
          "positionKind": "authored-spawn"
        },
        {
          "id": 464,
          "name": "Raz3",
          "x": 1800,
          "y": 1025,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 315,
          "name": "Raz3",
          "x": 1691,
          "y": 1049,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        },
        {
          "id": 319,
          "name": "Raz3",
          "x": 1829,
          "y": 1058,
          "spriteId": 69,
          "positionKind": "authored-spawn"
        },
        {
          "id": 463,
          "name": "Raz3",
          "x": 1723,
          "y": 1094,
          "spriteId": 70,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "finala",
      "engineId": "FINALA",
      "title": "Unknown Plane \u2014 approach",
      "image": "images/alqadim-atlas/finala.png",
      "roofImage": "images/alqadim-atlas/finala-roofed.png",
      "width": 1776,
      "height": 1408,
      "mapWidth": 111,
      "mapHeight": 88,
      "tileSize": 16,
      "tileBits": 7,
      "tileCount": 67,
      "annotationKey": "map_unknown_plane.png",
      "manualImage": "images/alqadim/map_unknown_plane.png",
      "sourceFile": "WORLDS/FINALA.LIB",
      "sourceBytes": 285867,
      "sourceSha256": "970c108f959b5e7431b6718e33a55e92676ee062a54fd1b4c4bd6520248981d6",
      "sceneryCount": 236,
      "foregroundCount": 7,
      "actorCount": 55,
      "namedActors": [
        {
          "id": 76,
          "name": "Sor2",
          "x": 471,
          "y": 90,
          "spriteId": 89,
          "positionKind": "authored-spawn"
        },
        {
          "id": 68,
          "name": "Nas3",
          "x": 917,
          "y": 90,
          "spriteId": 54,
          "positionKind": "authored-spawn"
        },
        {
          "id": 74,
          "name": "Sor1",
          "x": 1286,
          "y": 134,
          "spriteId": 84,
          "positionKind": "authored-spawn"
        },
        {
          "id": 243,
          "name": "Sor1",
          "x": 1320,
          "y": 137,
          "spriteId": 89,
          "positionKind": "authored-spawn"
        },
        {
          "id": 73,
          "name": "Sor2 (",
          "x": 1715,
          "y": 329,
          "spriteId": 82,
          "positionKind": "authored-spawn"
        },
        {
          "id": 235,
          "name": "Nameless1 d",
          "x": 272,
          "y": 360,
          "spriteId": 23,
          "positionKind": "authored-spawn"
        },
        {
          "id": 67,
          "name": "Nas2",
          "x": 682,
          "y": 430,
          "spriteId": 47,
          "positionKind": "authored-spawn"
        },
        {
          "id": 69,
          "name": "Nas4",
          "x": 968,
          "y": 433,
          "spriteId": 51,
          "positionKind": "authored-spawn"
        },
        {
          "id": 244,
          "name": "Cyc3",
          "x": 1713,
          "y": 633,
          "spriteId": 106,
          "positionKind": "authored-spawn"
        },
        {
          "id": 151,
          "name": "Cyc3",
          "x": 1434,
          "y": 739,
          "spriteId": 109,
          "positionKind": "authored-spawn"
        },
        {
          "id": 66,
          "name": "Nas1",
          "x": 920,
          "y": 1029,
          "spriteId": 54,
          "positionKind": "authored-spawn"
        },
        {
          "id": 71,
          "name": "Cyc2",
          "x": 1469,
          "y": 1038,
          "spriteId": 109,
          "positionKind": "authored-spawn"
        },
        {
          "id": 241,
          "name": "Nas5",
          "x": 689,
          "y": 1110,
          "spriteId": 51,
          "positionKind": "authored-spawn"
        },
        {
          "id": 64,
          "name": "Nas1",
          "x": 931,
          "y": 1124,
          "spriteId": 54,
          "positionKind": "authored-spawn"
        },
        {
          "id": 65,
          "name": "Nas1",
          "x": 901,
          "y": 1126,
          "spriteId": 54,
          "positionKind": "authored-spawn"
        },
        {
          "id": 208,
          "name": "Nas5",
          "x": 601,
          "y": 1182,
          "spriteId": 51,
          "positionKind": "authored-spawn"
        },
        {
          "id": 253,
          "name": "Arrow5",
          "x": 818,
          "y": 1231,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 357,
          "name": "Nameless2 P",
          "x": 1531,
          "y": 1241,
          "spriteId": 32,
          "positionKind": "authored-spawn"
        },
        {
          "id": 252,
          "name": "Arrow4",
          "x": 818,
          "y": 1244,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 254,
          "name": "Arrow6",
          "x": 816,
          "y": 1254,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 249,
          "name": "Arrow1",
          "x": 815,
          "y": 1264,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 209,
          "name": "Nas5",
          "x": 565,
          "y": 1265,
          "spriteId": 51,
          "positionKind": "authored-spawn"
        },
        {
          "id": 250,
          "name": "Arrow2",
          "x": 816,
          "y": 1273,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 251,
          "name": "Arrow3",
          "x": 814,
          "y": 1281,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 274,
          "name": "Arrow10",
          "x": 802,
          "y": 1333,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 275,
          "name": "Arrow11",
          "x": 801,
          "y": 1341,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 276,
          "name": "Arrow12",
          "x": 801,
          "y": 1348,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 70,
          "name": "Cyc1",
          "x": 1357,
          "y": 1356,
          "spriteId": 109,
          "positionKind": "authored-spawn"
        },
        {
          "id": 210,
          "name": "Nas5",
          "x": 646,
          "y": 1361,
          "spriteId": 47,
          "positionKind": "authored-spawn"
        },
        {
          "id": 211,
          "name": "Nas5",
          "x": 591,
          "y": 1367,
          "spriteId": 47,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell F",
          "x": 919,
          "y": 1374,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "finalb",
      "engineId": "FINALB",
      "title": "Unknown Plane \u2014 finale",
      "image": "images/alqadim-atlas/finalb.png",
      "roofImage": null,
      "width": 2048,
      "height": 1280,
      "mapWidth": 128,
      "mapHeight": 80,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 183,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/FINALB.LIB",
      "sourceBytes": 369399,
      "sourceSha256": "0b8dece20d9f6bcbbacac2bf016d3fae9e2f2d45f3a282b2ad3e4e0ca4747b62",
      "sceneryCount": 202,
      "foregroundCount": 0,
      "actorCount": 23,
      "namedActors": [
        {
          "id": 224,
          "name": "ert Mitchell",
          "x": 1000,
          "y": 127,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 218,
          "name": "Ogrima",
          "x": 246,
          "y": 186,
          "spriteId": 205,
          "positionKind": "authored-spawn"
        },
        {
          "id": 277,
          "name": "Nameless3",
          "x": 1058,
          "y": 187,
          "spriteId": 35,
          "positionKind": "authored-spawn"
        },
        {
          "id": 219,
          "name": "Merc",
          "x": 759,
          "y": 590,
          "spriteId": 83,
          "positionKind": "authored-spawn"
        },
        {
          "id": 222,
          "name": "A",
          "x": 1656,
          "y": 879,
          "spriteId": 232,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell F",
          "x": 1721,
          "y": 956,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 275,
          "name": "Nameless4",
          "x": 1011,
          "y": 1136,
          "spriteId": 6,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "hermita",
      "engineId": "HERMITA",
      "title": "Isle of Shibaz \u2014 first region",
      "image": "images/alqadim-atlas/hermita.png",
      "roofImage": "images/alqadim-atlas/hermita-roofed.png",
      "width": 2048,
      "height": 2048,
      "mapWidth": 128,
      "mapHeight": 128,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 443,
      "annotationKey": "map_isle_shibaz_l1.png",
      "manualImage": "images/alqadim/map_isle_shibaz_l1.png",
      "sourceFile": "WORLDS/HERMITA.LIB",
      "sourceBytes": 326176,
      "sourceSha256": "8574b22302940689e6331b57d990cc48574a9dfbc88b7605c5abf08f21e3854b",
      "sceneryCount": 376,
      "foregroundCount": 4,
      "actorCount": 74,
      "namedActors": [
        {
          "id": 317,
          "name": "Ashid",
          "x": 127,
          "y": 33,
          "spriteId": 7,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell 2",
          "x": 222,
          "y": 431,
          "spriteId": 16,
          "positionKind": "authored-spawn"
        },
        {
          "id": 171,
          "name": "Rashidin",
          "x": 335,
          "y": 637,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 105,
          "name": "Talkchest",
          "x": 495,
          "y": 866,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 346,
          "name": "Chestavenger",
          "x": 202,
          "y": 908,
          "spriteId": 108,
          "positionKind": "authored-spawn"
        },
        {
          "id": 194,
          "name": "Chestavenger",
          "x": 235,
          "y": 914,
          "spriteId": 108,
          "positionKind": "authored-spawn"
        },
        {
          "id": 527,
          "name": "Chestavenger",
          "x": 846,
          "y": 1353,
          "spriteId": 112,
          "positionKind": "authored-spawn"
        },
        {
          "id": 525,
          "name": "Chestavenger",
          "x": 843,
          "y": 1522,
          "spriteId": 104,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "hermitb",
      "engineId": "HERMITB",
      "title": "Isle of Shibaz \u2014 second region",
      "image": "images/alqadim-atlas/hermitb.png",
      "roofImage": null,
      "width": 2016,
      "height": 2048,
      "mapWidth": 126,
      "mapHeight": 128,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 260,
      "annotationKey": "map_isle_shibaz_l2.png",
      "manualImage": "images/alqadim/map_isle_shibaz_l2.png",
      "sourceFile": "WORLDS/HERMITB.LIB",
      "sourceBytes": 300268,
      "sourceSha256": "c54d6054f32a263021b433db60b02d61f6ecf75bfaf54e67772536c882a63d63",
      "sceneryCount": 793,
      "foregroundCount": 0,
      "actorCount": 39,
      "namedActors": [
        {
          "id": 809,
          "name": "Felemental",
          "x": 1302,
          "y": 246,
          "spriteId": 7,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Good Name ell m",
          "x": 406,
          "y": 263,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 914,
          "name": "Chasestatue3",
          "x": 1229,
          "y": 568,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 154,
          "name": "Chasestatue1",
          "x": 1117,
          "y": 578,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 913,
          "name": "Chasestatue2",
          "x": 1021,
          "y": 608,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 359,
          "name": "Rashidin",
          "x": 398,
          "y": 640,
          "spriteId": 22,
          "positionKind": "authored-spawn"
        },
        {
          "id": 430,
          "name": "Rashidin's shadow",
          "x": 449,
          "y": 657,
          "spriteId": 13,
          "positionKind": "authored-spawn"
        },
        {
          "id": 981,
          "name": "Carpet",
          "x": 445,
          "y": 838,
          "spriteId": 10,
          "positionKind": "authored-spawn"
        },
        {
          "id": 332,
          "name": "Puzstatue5 3",
          "x": 137,
          "y": 857,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 272,
          "name": "PC's Carpet shadow",
          "x": 434,
          "y": 860,
          "spriteId": 13,
          "positionKind": "authored-spawn"
        },
        {
          "id": 140,
          "name": "Felemental",
          "x": 750,
          "y": 864,
          "spriteId": 7,
          "positionKind": "authored-spawn"
        },
        {
          "id": 330,
          "name": "Puzstatue3 3",
          "x": 103,
          "y": 870,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 329,
          "name": "Puzstatue2 3",
          "x": 169,
          "y": 870,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 331,
          "name": "Puzstatue4 3",
          "x": 197,
          "y": 891,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 319,
          "name": "Puzstatue1 3",
          "x": 73,
          "y": 892,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 340,
          "name": "Puzstatue6 3",
          "x": 282,
          "y": 1122,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 201,
          "name": "Guardian",
          "x": 58,
          "y": 1239,
          "spriteId": 53,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "hermitc",
      "engineId": "HERMITC",
      "title": "Isle of Shibaz \u2014 third region",
      "image": "images/alqadim-atlas/hermitc.png",
      "roofImage": null,
      "width": 1968,
      "height": 1936,
      "mapWidth": 123,
      "mapHeight": 121,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 259,
      "annotationKey": "map_isle_shibaz_l3.png",
      "manualImage": "images/alqadim/map_isle_shibaz_l3.png",
      "sourceFile": "WORLDS/HERMITC.LIB",
      "sourceBytes": 270282,
      "sourceSha256": "ffc6846a3cc42f76e566690eaead7b7501b226988492ad1dbeeb498e3eedda34",
      "sceneryCount": 173,
      "foregroundCount": 0,
      "actorCount": 45,
      "namedActors": [
        {
          "id": 77,
          "name": "Rashidin",
          "x": 170,
          "y": 51,
          "spriteId": 12,
          "positionKind": "authored-spawn"
        },
        {
          "id": 81,
          "name": "Marcher1",
          "x": 243,
          "y": 86,
          "spriteId": 124,
          "positionKind": "authored-spawn"
        },
        {
          "id": 145,
          "name": "Marcher1",
          "x": 511,
          "y": 86,
          "spriteId": 124,
          "positionKind": "authored-spawn"
        },
        {
          "id": 80,
          "name": "Casket_b",
          "x": 916,
          "y": 244,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Bert Mitchell 2",
          "x": 327,
          "y": 701,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 79,
          "name": "Casket_a",
          "x": 1342,
          "y": 1184,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 226,
          "name": "Julie",
          "x": 1191,
          "y": 1825,
          "spriteId": 29,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "hold",
      "engineId": "HOLD",
      "title": "Rotting Ships' Hold",
      "image": "images/alqadim-atlas/hold.png",
      "roofImage": "images/alqadim-atlas/hold-roofed.png",
      "width": 320,
      "height": 512,
      "mapWidth": 20,
      "mapHeight": 32,
      "tileSize": 16,
      "tileBits": 6,
      "tileCount": 62,
      "annotationKey": "map_rotting_ships_hold.png",
      "manualImage": "images/alqadim/map_rotting_ships_hold.png",
      "sourceFile": "WORLDS/HOLD.LIB",
      "sourceBytes": 70433,
      "sourceSha256": "66216de29e4eba14b81aaa11de16dd91b0e1873497341488afbbcf31ee82e07e",
      "sceneryCount": 28,
      "foregroundCount": 3,
      "actorCount": 2,
      "namedActors": [
        {
          "id": 8,
          "name": "Bert Mitchell",
          "x": 174,
          "y": 173,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 93,
          "name": "Your_brother",
          "x": 160,
          "y": 501,
          "spriteId": 12,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "lordsa",
      "engineId": "LORDSA",
      "title": "Sorcerer's Tower \u2014 first region",
      "image": "images/alqadim-atlas/lordsa.png",
      "roofImage": null,
      "width": 2048,
      "height": 1360,
      "mapWidth": 128,
      "mapHeight": 85,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 224,
      "annotationKey": "map_sorcerers_tower_l1.png",
      "manualImage": "images/alqadim/map_sorcerers_tower_l1.png",
      "sourceFile": "WORLDS/LORDSA.LIB",
      "sourceBytes": 201113,
      "sourceSha256": "838c75b7bed4c5de4bdce1246af7318a9600e393be9647dd44169b314d01caf4",
      "sceneryCount": 357,
      "foregroundCount": 0,
      "actorCount": 4,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 688,
          "y": 133,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 401,
          "name": "Djinngate",
          "x": 689,
          "y": 585,
          "spriteId": 36,
          "positionKind": "authored-spawn"
        },
        {
          "id": 475,
          "name": "Shahar Izad",
          "x": 839,
          "y": 639,
          "spriteId": 17,
          "positionKind": "authored-spawn"
        },
        {
          "id": 404,
          "name": "Daogate",
          "x": 1377,
          "y": 730,
          "spriteId": 16,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "lordsb",
      "engineId": "LORDSB",
      "title": "Sorcerer's Tower \u2014 second region",
      "image": "images/alqadim-atlas/lordsb.png",
      "roofImage": null,
      "width": 848,
      "height": 1120,
      "mapWidth": 53,
      "mapHeight": 70,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 206,
      "annotationKey": "map_sorcerers_tower_l2.png",
      "manualImage": "images/alqadim/map_sorcerers_tower_l2.png",
      "sourceFile": "WORLDS/LORDSB.LIB",
      "sourceBytes": 134950,
      "sourceSha256": "b0f38bd019246a81ce770692690589a5a8258965c68bfba6519741940219e176",
      "sceneryCount": 31,
      "foregroundCount": 0,
      "actorCount": 11,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell <",
          "x": 435,
          "y": 266,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 71,
          "name": "nasnas1",
          "x": 753,
          "y": 301,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 70,
          "name": "nasnas1",
          "x": 638,
          "y": 314,
          "spriteId": 36,
          "positionKind": "authored-spawn"
        },
        {
          "id": 81,
          "name": "nasnas2",
          "x": 757,
          "y": 333,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 82,
          "name": "nasnas2",
          "x": 642,
          "y": 340,
          "spriteId": 36,
          "positionKind": "authored-spawn"
        },
        {
          "id": 84,
          "name": "nasnas3",
          "x": 757,
          "y": 360,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 83,
          "name": "nasnas3",
          "x": 641,
          "y": 363,
          "spriteId": 36,
          "positionKind": "authored-spawn"
        },
        {
          "id": 86,
          "name": "nasnas4",
          "x": 610,
          "y": 381,
          "spriteId": 36,
          "positionKind": "authored-spawn"
        },
        {
          "id": 85,
          "name": "nasnas4",
          "x": 753,
          "y": 388,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 72,
          "name": "Daoherald",
          "x": 496,
          "y": 442,
          "spriteId": 31,
          "positionKind": "authored-spawn"
        },
        {
          "id": 74,
          "name": "Shaharizad",
          "x": 611,
          "y": 653,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "lordsc",
      "engineId": "LORDSC",
      "title": "Sorcerer's Tower \u2014 third region",
      "image": "images/alqadim-atlas/lordsc.png",
      "roofImage": null,
      "width": 992,
      "height": 576,
      "mapWidth": 62,
      "mapHeight": 36,
      "tileSize": 16,
      "tileBits": 7,
      "tileCount": 79,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/LORDSC.LIB",
      "sourceBytes": 104902,
      "sourceSha256": "4250a27856497916c158c6dc1ee5b9dfed1aac32e5149e806419d1140bc2f4e8",
      "sceneryCount": 165,
      "foregroundCount": 0,
      "actorCount": 2,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 382,
          "y": 546,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "lordsd",
      "engineId": "LORDSD",
      "title": "Sorcerer's Tower \u2014 fourth region",
      "image": "images/alqadim-atlas/lordsd.png",
      "roofImage": null,
      "width": 640,
      "height": 608,
      "mapWidth": 40,
      "mapHeight": 38,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 173,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/LORDSD.LIB",
      "sourceBytes": 79962,
      "sourceSha256": "d3a297ae091ea465db2be874bf440cfc0fd9f63691595d18f3c01b7b17d64f78",
      "sceneryCount": 16,
      "foregroundCount": 0,
      "actorCount": 2,
      "namedActors": [
        {
          "id": 85,
          "name": "Shaharizad",
          "x": 307,
          "y": 526,
          "spriteId": 12,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 336,
          "y": 564,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "lordse",
      "engineId": "LORDSE",
      "title": "Sorcerer's Tower \u2014 final chamber",
      "image": "images/alqadim-atlas/lordse.png",
      "roofImage": null,
      "width": 320,
      "height": 320,
      "mapWidth": 20,
      "mapHeight": 20,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 199,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/LORDSE.LIB",
      "sourceBytes": 72538,
      "sourceSha256": "d67ea99094e0c06daf48b2d11a7a81a92ca51e81b71580999e25ac123e0bbe12",
      "sceneryCount": 0,
      "foregroundCount": 0,
      "actorCount": 3,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 155,
          "y": 74,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 65,
          "name": "Satarah",
          "x": 189,
          "y": 159,
          "spriteId": 3,
          "positionKind": "authored-spawn"
        },
        {
          "id": 64,
          "name": "Bubishah",
          "x": 135,
          "y": 160,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "magroom",
      "engineId": "MAGROOM",
      "title": "Isle of Hajar \u2014 magic room",
      "image": "images/alqadim-atlas/magroom.png",
      "roofImage": null,
      "width": 640,
      "height": 400,
      "mapWidth": 40,
      "mapHeight": 25,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 185,
      "annotationKey": "map_isle_hajar.png",
      "manualImage": "images/alqadim/map_isle_hajar.png",
      "sourceFile": "WORLDS/MAGROOM.LIB",
      "sourceBytes": 61503,
      "sourceSha256": "e6d460b05a6b55dd6de86ac727d28c2a9586ae698a091534089c8193753c3640",
      "sceneryCount": 18,
      "foregroundCount": 0,
      "actorCount": 1,
      "namedActors": [
        {
          "id": 8,
          "name": "Bert Mitchell d",
          "x": 148,
          "y": 333,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "newdung",
      "engineId": "NEWDUNG",
      "title": "Caliph's New Dungeon",
      "image": "images/alqadim-atlas/newdung.png",
      "roofImage": null,
      "width": 2016,
      "height": 1920,
      "mapWidth": 126,
      "mapHeight": 120,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 156,
      "annotationKey": "map_caliphs_new_dungeon.png",
      "manualImage": "images/alqadim/map_caliphs_new_dungeon.png",
      "sourceFile": "WORLDS/NEWDUNG.LIB",
      "sourceBytes": 136444,
      "sourceSha256": "12126e96bcf33f2349ee55739a1a3cba3704b5b7866305c5a477bbd5510ac30b",
      "sceneryCount": 95,
      "foregroundCount": 0,
      "actorCount": 20,
      "namedActors": [
        {
          "id": 103,
          "name": "Patrol1",
          "x": 300,
          "y": 445,
          "spriteId": 13,
          "positionKind": "authored-spawn"
        },
        {
          "id": 70,
          "name": "Alhazrad",
          "x": 207,
          "y": 460,
          "spriteId": 59,
          "positionKind": "authored-spawn"
        },
        {
          "id": 160,
          "name": "New_robots",
          "x": 245,
          "y": 588,
          "spriteId": 39,
          "positionKind": "authored-spawn"
        },
        {
          "id": 169,
          "name": "New_robots",
          "x": 765,
          "y": 633,
          "spriteId": 39,
          "positionKind": "authored-spawn"
        },
        {
          "id": 170,
          "name": "New_robots",
          "x": 212,
          "y": 675,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 168,
          "name": "New_robots",
          "x": 1297,
          "y": 745,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 162,
          "name": "New_robots",
          "x": 789,
          "y": 812,
          "spriteId": 39,
          "positionKind": "authored-spawn"
        },
        {
          "id": 163,
          "name": "New_robots",
          "x": 718,
          "y": 921,
          "spriteId": 43,
          "positionKind": "authored-spawn"
        },
        {
          "id": 164,
          "name": "New_robots",
          "x": 983,
          "y": 952,
          "spriteId": 45,
          "positionKind": "authored-spawn"
        },
        {
          "id": 72,
          "name": "New_robots",
          "x": 1304,
          "y": 966,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 154,
          "name": "New_robots",
          "x": 1827,
          "y": 994,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 79,
          "name": "Sumia",
          "x": 499,
          "y": 1010,
          "spriteId": 74,
          "positionKind": "authored-spawn"
        },
        {
          "id": 102,
          "name": "Dun_guard1",
          "x": 71,
          "y": 1177,
          "spriteId": 13,
          "positionKind": "authored-spawn"
        },
        {
          "id": 166,
          "name": "New_robots",
          "x": 1844,
          "y": 1191,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 121,
          "y": 1204,
          "spriteId": 16,
          "positionKind": "authored-spawn"
        },
        {
          "id": 167,
          "name": "New_robots",
          "x": 1281,
          "y": 1217,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 165,
          "name": "New_robots",
          "x": 712,
          "y": 1299,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "oasis",
      "engineId": "OASIS",
      "title": "Bandar al-Sadat",
      "image": "images/alqadim-atlas/oasis.png",
      "roofImage": null,
      "width": 2048,
      "height": 2048,
      "mapWidth": 128,
      "mapHeight": 128,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 394,
      "annotationKey": "map_bandar_al_sadat.png",
      "manualImage": "images/alqadim/map_bandar_al_sadat.png",
      "sourceFile": "WORLDS/OASIS.LIB",
      "sourceBytes": 230178,
      "sourceSha256": "33500bace7b2d74a51e398986c410e1ef700fe0a8d1619e72f120f778409b682",
      "sceneryCount": 127,
      "foregroundCount": 0,
      "actorCount": 78,
      "namedActors": [
        {
          "id": 163,
          "name": "debbi",
          "x": 979,
          "y": 890,
          "spriteId": 38,
          "positionKind": "authored-spawn"
        },
        {
          "id": 162,
          "name": "debbi",
          "x": 910,
          "y": 940,
          "spriteId": 34,
          "positionKind": "authored-spawn"
        },
        {
          "id": 165,
          "name": "debbi",
          "x": 1063,
          "y": 942,
          "spriteId": 34,
          "positionKind": "authored-spawn"
        },
        {
          "id": 161,
          "name": "Caliph",
          "x": 993,
          "y": 948,
          "spriteId": 8,
          "positionKind": "authored-spawn"
        },
        {
          "id": 164,
          "name": "debbi",
          "x": 984,
          "y": 985,
          "spriteId": 30,
          "positionKind": "authored-spawn"
        },
        {
          "id": 159,
          "name": "Pahari",
          "x": 1517,
          "y": 1065,
          "spriteId": 24,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 1872,
          "y": 1737,
          "spriteId": 16,
          "positionKind": "authored-spawn"
        },
        {
          "id": 208,
          "name": "Turtleb",
          "x": 434,
          "y": 1886,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "ogrima",
      "engineId": "OGRIMA",
      "title": "Isle of Jaza'ir Jiza",
      "image": "images/alqadim-atlas/ogrima.png",
      "roofImage": null,
      "width": 1712,
      "height": 1248,
      "mapWidth": 107,
      "mapHeight": 78,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 221,
      "annotationKey": "map_isle_jaza_ir_jiza.png",
      "manualImage": "images/alqadim/map_isle_jaza_ir_jiza.png",
      "sourceFile": "WORLDS/OGRIMA.LIB",
      "sourceBytes": 144956,
      "sourceSha256": "d43f5bba9371e12f8072275d6027659d388ac1d068838070cc9c629f9fe7608b",
      "sceneryCount": 159,
      "foregroundCount": 0,
      "actorCount": 21,
      "namedActors": [
        {
          "id": 115,
          "name": "chest",
          "x": 685,
          "y": 321,
          "spriteId": 5,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell <",
          "x": 252,
          "y": 482,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "olddung",
      "engineId": "OLDDUNG",
      "title": "Old Dungeon",
      "image": "images/alqadim-atlas/olddung.png",
      "roofImage": null,
      "width": 1360,
      "height": 1248,
      "mapWidth": 85,
      "mapHeight": 78,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 225,
      "annotationKey": "map_old_dungeon.png",
      "manualImage": "images/alqadim/map_old_dungeon.png",
      "sourceFile": "WORLDS/OLDDUNG.LIB",
      "sourceBytes": 280924,
      "sourceSha256": "18fc004c8c450a051aec1242a9c9a25d8a4caac36f7e669762d89f2804d9c445",
      "sceneryCount": 97,
      "foregroundCount": 0,
      "actorCount": 46,
      "namedActors": [
        {
          "id": 122,
          "name": "Pangar2 ek d",
          "x": 546,
          "y": 70,
          "spriteId": 11,
          "positionKind": "authored-spawn"
        },
        {
          "id": 102,
          "name": "Pangar1 ek d",
          "x": 734,
          "y": 81,
          "spriteId": 154,
          "positionKind": "authored-spawn"
        },
        {
          "id": 200,
          "name": "Od_zombie",
          "x": 1060,
          "y": 92,
          "spriteId": 56,
          "positionKind": "authored-spawn"
        },
        {
          "id": 202,
          "name": "Od_zombie",
          "x": 961,
          "y": 101,
          "spriteId": 56,
          "positionKind": "authored-spawn"
        },
        {
          "id": 169,
          "name": "Od_zombie",
          "x": 878,
          "y": 104,
          "spriteId": 56,
          "positionKind": "authored-spawn"
        },
        {
          "id": 205,
          "name": "Od_zombie",
          "x": 1106,
          "y": 107,
          "spriteId": 56,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell <",
          "x": 334,
          "y": 304,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 99,
          "name": "Od_boar",
          "x": 454,
          "y": 426,
          "spriteId": 227,
          "positionKind": "authored-spawn"
        },
        {
          "id": 254,
          "name": "Od_boar",
          "x": 392,
          "y": 461,
          "spriteId": 223,
          "positionKind": "authored-spawn"
        },
        {
          "id": 209,
          "name": "Od_ghoul",
          "x": 716,
          "y": 688,
          "spriteId": 179,
          "positionKind": "authored-spawn"
        },
        {
          "id": 211,
          "name": "Od_ghoul",
          "x": 767,
          "y": 689,
          "spriteId": 179,
          "positionKind": "authored-spawn"
        },
        {
          "id": 212,
          "name": "Od_ghoul2",
          "x": 1118,
          "y": 689,
          "spriteId": 179,
          "positionKind": "authored-spawn"
        },
        {
          "id": 175,
          "name": "Od_ghul1",
          "x": 929,
          "y": 695,
          "spriteId": 128,
          "positionKind": "authored-spawn"
        },
        {
          "id": 168,
          "name": "Od_ghoul2",
          "x": 1051,
          "y": 698,
          "spriteId": 179,
          "positionKind": "authored-spawn"
        },
        {
          "id": 223,
          "name": "Od_spider2",
          "x": 567,
          "y": 760,
          "spriteId": 32,
          "positionKind": "authored-spawn"
        },
        {
          "id": 221,
          "name": "Od_earth",
          "x": 1142,
          "y": 943,
          "spriteId": 74,
          "positionKind": "authored-spawn"
        },
        {
          "id": 218,
          "name": "Od_ghul3",
          "x": 886,
          "y": 954,
          "spriteId": 120,
          "positionKind": "authored-spawn"
        },
        {
          "id": 219,
          "name": "Od_earth",
          "x": 1114,
          "y": 961,
          "spriteId": 74,
          "positionKind": "authored-spawn"
        },
        {
          "id": 177,
          "name": "Od_slime",
          "x": 398,
          "y": 964,
          "spriteId": 92,
          "positionKind": "authored-spawn"
        },
        {
          "id": 214,
          "name": "Od_slime",
          "x": 487,
          "y": 969,
          "spriteId": 92,
          "positionKind": "authored-spawn"
        },
        {
          "id": 216,
          "name": "Od_slime",
          "x": 536,
          "y": 970,
          "spriteId": 116,
          "positionKind": "authored-spawn"
        },
        {
          "id": 217,
          "name": "Od_ghul2",
          "x": 693,
          "y": 1211,
          "spriteId": 208,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "opener",
      "engineId": "OPENER",
      "title": "Testing Grounds",
      "image": "images/alqadim-atlas/opener.png",
      "roofImage": null,
      "width": 2048,
      "height": 1760,
      "mapWidth": 128,
      "mapHeight": 110,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 255,
      "annotationKey": "map_testing_grounds.png",
      "manualImage": "images/alqadim/map_testing_grounds.png",
      "sourceFile": "WORLDS/OPENER.LIB",
      "sourceBytes": 207898,
      "sourceSha256": "9197ce604ef75f4818fa7cf4167dde18472a6cd576d7406e152a2fe62d0cf349",
      "sceneryCount": 494,
      "foregroundCount": 0,
      "actorCount": 66,
      "namedActors": [
        {
          "id": 156,
          "name": "Arrow1",
          "x": 104,
          "y": 76,
          "spriteId": 67,
          "positionKind": "authored-spawn"
        },
        {
          "id": 157,
          "name": "Arrow2",
          "x": 103,
          "y": 88,
          "spriteId": 67,
          "positionKind": "authored-spawn"
        },
        {
          "id": 158,
          "name": "Arrow3",
          "x": 103,
          "y": 101,
          "spriteId": 67,
          "positionKind": "authored-spawn"
        },
        {
          "id": 159,
          "name": "Arrow4",
          "x": 102,
          "y": 132,
          "spriteId": 71,
          "positionKind": "authored-spawn"
        },
        {
          "id": 160,
          "name": "Arrow5",
          "x": 102,
          "y": 145,
          "spriteId": 71,
          "positionKind": "authored-spawn"
        },
        {
          "id": 627,
          "name": "O_fe7",
          "x": 758,
          "y": 146,
          "spriteId": 33,
          "positionKind": "authored-spawn"
        },
        {
          "id": 161,
          "name": "Arrow6",
          "x": 102,
          "y": 156,
          "spriteId": 71,
          "positionKind": "authored-spawn"
        },
        {
          "id": 626,
          "name": "O_fe7",
          "x": 829,
          "y": 156,
          "spriteId": 33,
          "positionKind": "authored-spawn"
        },
        {
          "id": 342,
          "name": "O_fe1",
          "x": 1767,
          "y": 577,
          "spriteId": 33,
          "positionKind": "authored-spawn"
        },
        {
          "id": 334,
          "name": "O_fe1",
          "x": 1805,
          "y": 589,
          "spriteId": 33,
          "positionKind": "authored-spawn"
        },
        {
          "id": 577,
          "name": "O_fe5",
          "x": 824,
          "y": 864,
          "spriteId": 33,
          "positionKind": "authored-spawn"
        },
        {
          "id": 154,
          "name": "Teleport",
          "x": 223,
          "y": 1305,
          "spriteId": 1,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 245,
          "y": 1688,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "pal0",
      "engineId": "PAL0",
      "title": "Palace Facade",
      "image": "images/alqadim-atlas/pal0.png",
      "roofImage": "images/alqadim-atlas/pal0-roofed.png",
      "width": 2048,
      "height": 2048,
      "mapWidth": 128,
      "mapHeight": 128,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 152,
      "annotationKey": "map_palace_facade.png",
      "manualImage": "images/alqadim/map_palace_facade.png",
      "sourceFile": "WORLDS/PAL0.LIB",
      "sourceBytes": 264510,
      "sourceSha256": "b7b62c30dacdce96c46f98b36166ead7a3158c4e8b2652a25d30d4fb3a8a0b70",
      "sceneryCount": 304,
      "foregroundCount": 35,
      "actorCount": 52,
      "namedActors": [
        {
          "id": 476,
          "name": "Pangar2 ek",
          "x": 1595,
          "y": 339,
          "spriteId": 99,
          "positionKind": "authored-spawn"
        },
        {
          "id": 266,
          "name": "Servant6",
          "x": 1459,
          "y": 357,
          "spriteId": 17,
          "positionKind": "authored-spawn"
        },
        {
          "id": 264,
          "name": "Alia",
          "x": 1521,
          "y": 358,
          "spriteId": 54,
          "positionKind": "authored-spawn"
        },
        {
          "id": 258,
          "name": "Servant7",
          "x": 1482,
          "y": 360,
          "spriteId": 34,
          "positionKind": "authored-spawn"
        },
        {
          "id": 244,
          "name": "Patrolguard",
          "x": 890,
          "y": 460,
          "spriteId": 68,
          "positionKind": "authored-spawn"
        },
        {
          "id": 243,
          "name": "Servant5",
          "x": 1350,
          "y": 553,
          "spriteId": 18,
          "positionKind": "authored-spawn"
        },
        {
          "id": 263,
          "name": "Caliph",
          "x": 1019,
          "y": 614,
          "spriteId": 4,
          "positionKind": "authored-spawn"
        },
        {
          "id": 245,
          "name": "Teacart",
          "x": 379,
          "y": 615,
          "spriteId": 118,
          "positionKind": "authored-spawn"
        },
        {
          "id": 352,
          "name": "Haremguard1",
          "x": 291,
          "y": 629,
          "spriteId": 69,
          "positionKind": "authored-spawn"
        },
        {
          "id": 365,
          "name": "Haremguard2",
          "x": 438,
          "y": 629,
          "spriteId": 69,
          "positionKind": "authored-spawn"
        },
        {
          "id": 256,
          "name": "Shall'Azim",
          "x": 975,
          "y": 659,
          "spriteId": 116,
          "positionKind": "authored-spawn"
        },
        {
          "id": 268,
          "name": "Servant4",
          "x": 1352,
          "y": 692,
          "spriteId": 32,
          "positionKind": "authored-spawn"
        },
        {
          "id": 329,
          "name": "Servant3",
          "x": 1450,
          "y": 850,
          "spriteId": 34,
          "positionKind": "authored-spawn"
        },
        {
          "id": 464,
          "name": "Pal_guard1",
          "x": 706,
          "y": 973,
          "spriteId": 69,
          "positionKind": "authored-spawn"
        },
        {
          "id": 489,
          "name": "Pal_guard2",
          "x": 846,
          "y": 1082,
          "spriteId": 69,
          "positionKind": "authored-spawn"
        },
        {
          "id": 285,
          "name": "Corsair1",
          "x": 1007,
          "y": 1101,
          "spriteId": 117,
          "positionKind": "authored-spawn"
        },
        {
          "id": 253,
          "name": "Sabahar",
          "x": 128,
          "y": 1386,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 393,
          "name": "Servant1",
          "x": 1426,
          "y": 1497,
          "spriteId": 18,
          "positionKind": "authored-spawn"
        },
        {
          "id": 356,
          "name": "Obdel",
          "x": 1572,
          "y": 1568,
          "spriteId": 90,
          "positionKind": "authored-spawn"
        },
        {
          "id": 283,
          "name": "Bashkin",
          "x": 1035,
          "y": 1715,
          "spriteId": 117,
          "positionKind": "authored-spawn"
        },
        {
          "id": 232,
          "name": "Vizier",
          "x": 1001,
          "y": 1733,
          "spriteId": 133,
          "positionKind": "authored-spawn"
        },
        {
          "id": 279,
          "name": "Servant1",
          "x": 955,
          "y": 1954,
          "spriteId": 18,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 997,
          "y": 1964,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 494,
          "name": "Pal_guard3",
          "x": 808,
          "y": 2004,
          "spriteId": 69,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "reef",
      "engineId": "REEF",
      "title": "Reef of the Dead",
      "image": "images/alqadim-atlas/reef.png",
      "roofImage": null,
      "width": 1712,
      "height": 1248,
      "mapWidth": 107,
      "mapHeight": 78,
      "tileSize": 16,
      "tileBits": 10,
      "tileCount": 521,
      "annotationKey": "map_reef_of_dead.png",
      "manualImage": "images/alqadim/map_reef_of_dead.png",
      "sourceFile": "WORLDS/REEF.LIB",
      "sourceBytes": 234366,
      "sourceSha256": "8a0f96040c510be71a89a5f3beb65e6e412908b7b67394b5f9c431a3c9dd813d",
      "sceneryCount": 169,
      "foregroundCount": 0,
      "actorCount": 33,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell  ",
          "x": 1243,
          "y": 274,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 176,
          "name": "Turtlea",
          "x": 1622,
          "y": 1216,
          "spriteId": 2,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "road",
      "engineId": "ROAD",
      "title": "Western Desert",
      "image": "images/alqadim-atlas/road.png",
      "roofImage": "images/alqadim-atlas/road-roofed.png",
      "width": 1456,
      "height": 2944,
      "mapWidth": 91,
      "mapHeight": 184,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 301,
      "annotationKey": "map_western_desert.png",
      "manualImage": "images/alqadim/map_western_desert.png",
      "sourceFile": "WORLDS/ROAD.LIB",
      "sourceBytes": 393953,
      "sourceSha256": "cdcc30e9a94199c19e4b9af16b6b14afbb7181e7469f5aa430e2992df8c23938",
      "sceneryCount": 443,
      "foregroundCount": 21,
      "actorCount": 40,
      "namedActors": [
        {
          "id": 542,
          "name": "Pangar2",
          "x": 705,
          "y": 47,
          "spriteId": 200,
          "positionKind": "authored-spawn"
        },
        {
          "id": 207,
          "name": "uard4",
          "x": 774,
          "y": 100,
          "spriteId": 42,
          "positionKind": "authored-spawn"
        },
        {
          "id": 219,
          "name": "Guard4",
          "x": 636,
          "y": 102,
          "spriteId": 42,
          "positionKind": "authored-spawn"
        },
        {
          "id": 222,
          "name": "Scamboy",
          "x": 1211,
          "y": 266,
          "spriteId": 115,
          "positionKind": "authored-spawn"
        },
        {
          "id": 296,
          "name": "uard4",
          "x": 635,
          "y": 402,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 237,
          "name": "uard4",
          "x": 831,
          "y": 423,
          "spriteId": 42,
          "positionKind": "authored-spawn"
        },
        {
          "id": 98,
          "name": "Zubakon",
          "x": 182,
          "y": 786,
          "spriteId": 165,
          "positionKind": "authored-spawn"
        },
        {
          "id": 239,
          "name": "uard4",
          "x": 964,
          "y": 871,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 243,
          "name": "uard4",
          "x": 497,
          "y": 873,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 497,
          "name": "gambler",
          "x": 300,
          "y": 952,
          "spriteId": 230,
          "positionKind": "authored-spawn"
        },
        {
          "id": 301,
          "name": "Zaratan_guy",
          "x": 685,
          "y": 1013,
          "spriteId": 135,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 729,
          "y": 1155,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 235,
          "name": "uard4",
          "x": 962,
          "y": 1232,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 629,
          "name": "uard4",
          "x": 494,
          "y": 1673,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 273,
          "name": "uard4",
          "x": 450,
          "y": 1851,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 628,
          "name": "uard4",
          "x": 501,
          "y": 1996,
          "spriteId": 41,
          "positionKind": "authored-spawn"
        },
        {
          "id": 220,
          "name": "Alleybeggar",
          "x": 1150,
          "y": 2001,
          "spriteId": 120,
          "positionKind": "authored-spawn"
        },
        {
          "id": 563,
          "name": "Pangar1",
          "x": 1443,
          "y": 2373,
          "spriteId": 212,
          "positionKind": "authored-spawn"
        },
        {
          "id": 205,
          "name": "Gateguard1",
          "x": 704,
          "y": 2380,
          "spriteId": 42,
          "positionKind": "authored-spawn"
        },
        {
          "id": 236,
          "name": "Gateguard1",
          "x": 803,
          "y": 2381,
          "spriteId": 42,
          "positionKind": "authored-spawn"
        },
        {
          "id": 407,
          "name": "Courier",
          "x": 23,
          "y": 2927,
          "spriteId": 24,
          "positionKind": "authored-spawn"
        },
        {
          "id": 408,
          "name": "Obdel",
          "x": 66,
          "y": 2928,
          "spriteId": 187,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "roadb",
      "engineId": "ROADB",
      "title": "Isle of Aballat",
      "image": "images/alqadim-atlas/roadb.png",
      "roofImage": null,
      "width": 1024,
      "height": 368,
      "mapWidth": 64,
      "mapHeight": 23,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 280,
      "annotationKey": "map_isle_aballat.png",
      "manualImage": "images/alqadim/map_isle_aballat.png",
      "sourceFile": "WORLDS/ROADB.LIB",
      "sourceBytes": 99342,
      "sourceSha256": "118f305ec46abb445491127f685c37fbd5a23bc3b986a71893b46420988c445a",
      "sceneryCount": 93,
      "foregroundCount": 0,
      "actorCount": 4,
      "namedActors": [
        {
          "id": 69,
          "name": "Pangar2",
          "x": 514,
          "y": 165,
          "spriteId": 10,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 230,
          "y": 243,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "senat",
      "engineId": "SENAT",
      "title": "Isle of Senat",
      "image": "images/alqadim-atlas/senat.png",
      "roofImage": null,
      "width": 1712,
      "height": 1248,
      "mapWidth": 107,
      "mapHeight": 78,
      "tileSize": 16,
      "tileBits": 8,
      "tileCount": 221,
      "annotationKey": "map_isle_senat.png",
      "manualImage": "images/alqadim/map_isle_senat.png",
      "sourceFile": "WORLDS/SENAT.LIB",
      "sourceBytes": 90856,
      "sourceSha256": "45080b38975029509a034c7b7e7036827f2e4f144902f33359905023ff90b41e",
      "sceneryCount": 259,
      "foregroundCount": 0,
      "actorCount": 22,
      "namedActors": [
        {
          "id": 8,
          "name": "Akbar itchell <",
          "x": 357,
          "y": 994,
          "spriteId": 16,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "shipa",
      "engineId": "SHIPA",
      "title": "The Ship",
      "image": "images/alqadim-atlas/shipa.png",
      "roofImage": null,
      "width": 624,
      "height": 832,
      "mapWidth": 39,
      "mapHeight": 52,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 332,
      "annotationKey": "map_the_ship.png",
      "manualImage": "images/alqadim/map_the_ship.png",
      "sourceFile": "WORLDS/SHIPA.LIB",
      "sourceBytes": 96811,
      "sourceSha256": "fc6f5dee4e73bdffc654e28603013c5c5e7db7efd825b67527bdf5ace7209f1e",
      "sceneryCount": 13,
      "foregroundCount": 0,
      "actorCount": 16,
      "namedActors": [
        {
          "id": 64,
          "name": "Captain",
          "x": 312,
          "y": 111,
          "spriteId": 0,
          "positionKind": "authored-spawn"
        },
        {
          "id": 101,
          "name": "Your_brother",
          "x": 140,
          "y": 404,
          "spriteId": 24,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Askar itchell F",
          "x": 186,
          "y": 407,
          "spriteId": 16,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "shipb",
      "engineId": "SHIPB",
      "title": "The Ship \u2014 later state",
      "image": "images/alqadim-atlas/shipb.png",
      "roofImage": null,
      "width": 1024,
      "height": 832,
      "mapWidth": 64,
      "mapHeight": 52,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 437,
      "annotationKey": null,
      "manualImage": null,
      "sourceFile": "WORLDS/SHIPB.LIB",
      "sourceBytes": 208778,
      "sourceSha256": "af7f1f300dac68bb8d7ab8e7d29fa8a918fc0aace55b5eb84f4859ab3671a155",
      "sceneryCount": 71,
      "foregroundCount": 0,
      "actorCount": 46,
      "namedActors": [
        {
          "id": 141,
          "name": "Pirate_chest",
          "x": 665,
          "y": 98,
          "spriteId": 4,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Bert Mitchell F",
          "x": 310,
          "y": 139,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "town",
      "engineId": "TOWN",
      "title": "Zaratan",
      "image": "images/alqadim-atlas/town.png",
      "roofImage": "images/alqadim-atlas/town-roofed.png",
      "width": 2048,
      "height": 2048,
      "mapWidth": 128,
      "mapHeight": 128,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 346,
      "annotationKey": "map_zaratan.png",
      "manualImage": "images/alqadim/map_zaratan.png",
      "sourceFile": "WORLDS/TOWN.LIB",
      "sourceBytes": 440535,
      "sourceSha256": "431ddd21611031f29dd9905176bbc1ad0f2d4a6e1901b2f8fe73aa8b52551672",
      "sceneryCount": 481,
      "foregroundCount": 25,
      "actorCount": 61,
      "namedActors": [
        {
          "id": 322,
          "name": "Qadis",
          "x": 742,
          "y": 222,
          "spriteId": 59,
          "positionKind": "authored-spawn"
        },
        {
          "id": 439,
          "name": "Zubakon aster",
          "x": 1104,
          "y": 238,
          "spriteId": 164,
          "positionKind": "authored-spawn"
        },
        {
          "id": 97,
          "name": "Family Genie",
          "x": 743,
          "y": 589,
          "spriteId": 208,
          "positionKind": "authored-spawn"
        },
        {
          "id": 423,
          "name": "Haroon abi Wassab",
          "x": 530,
          "y": 796,
          "spriteId": 72,
          "positionKind": "authored-spawn"
        },
        {
          "id": 424,
          "name": "Merwani bi Qassab",
          "x": 474,
          "y": 809,
          "spriteId": 27,
          "positionKind": "authored-spawn"
        },
        {
          "id": 165,
          "name": "Zubin al'Harat",
          "x": 1546,
          "y": 889,
          "spriteId": 149,
          "positionKind": "authored-spawn"
        },
        {
          "id": 125,
          "name": "Jessamin",
          "x": 1732,
          "y": 897,
          "spriteId": 14,
          "positionKind": "authored-spawn"
        },
        {
          "id": 415,
          "name": "Mamoon abi Qassab",
          "x": 457,
          "y": 993,
          "spriteId": 75,
          "positionKind": "authored-spawn"
        },
        {
          "id": 516,
          "name": "Latifah",
          "x": 674,
          "y": 1065,
          "spriteId": 184,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Akbar itchell",
          "x": 417,
          "y": 1128,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        },
        {
          "id": 496,
          "name": "Aliya",
          "x": 1000,
          "y": 1658,
          "spriteId": 44,
          "positionKind": "authored-spawn"
        },
        {
          "id": 670,
          "name": "Caliph",
          "x": 94,
          "y": 2038,
          "spriteId": 190,
          "positionKind": "authored-spawn"
        },
        {
          "id": 206,
          "name": "Sailor1",
          "x": 23,
          "y": 2042,
          "spriteId": 105,
          "positionKind": "authored-spawn"
        },
        {
          "id": 198,
          "name": "Sailor2",
          "x": 38,
          "y": 2042,
          "spriteId": 120,
          "positionKind": "authored-spawn"
        },
        {
          "id": 188,
          "name": "Rival_sailor2",
          "x": 71,
          "y": 2042,
          "spriteId": 90,
          "positionKind": "authored-spawn"
        },
        {
          "id": 193,
          "name": "Rival_sailo1",
          "x": 55,
          "y": 2043,
          "spriteId": 90,
          "positionKind": "authored-spawn"
        }
      ]
    },
    {
      "id": "voice",
      "engineId": "VOICE",
      "title": "Al-Naqqil",
      "image": "images/alqadim-atlas/voice.png",
      "roofImage": null,
      "width": 1712,
      "height": 1248,
      "mapWidth": 107,
      "mapHeight": 78,
      "tileSize": 16,
      "tileBits": 9,
      "tileCount": 366,
      "annotationKey": "map_al_naqqil.png",
      "manualImage": "images/alqadim/map_al_naqqil.png",
      "sourceFile": "WORLDS/VOICE.LIB",
      "sourceBytes": 287791,
      "sourceSha256": "26ebdc8e29f41ea0222d327851ba668abfc484b2ebbdcd2e6e385ab4df879af8",
      "sceneryCount": 99,
      "foregroundCount": 0,
      "actorCount": 27,
      "namedActors": [
        {
          "id": 78,
          "name": "Voice_werewolf",
          "x": 518,
          "y": 408,
          "spriteId": 28,
          "positionKind": "authored-spawn"
        },
        {
          "id": 69,
          "name": "Voice_pirates -",
          "x": 676,
          "y": 430,
          "spriteId": 113,
          "positionKind": "authored-spawn"
        },
        {
          "id": 77,
          "name": "Voice_ettin",
          "x": 973,
          "y": 435,
          "spriteId": 86,
          "positionKind": "authored-spawn"
        },
        {
          "id": 67,
          "name": "Voice_ammut",
          "x": 1004,
          "y": 608,
          "spriteId": 50,
          "positionKind": "authored-spawn"
        },
        {
          "id": 74,
          "name": "Voice_pirates",
          "x": 1030,
          "y": 753,
          "spriteId": 133,
          "positionKind": "authored-spawn"
        },
        {
          "id": 8,
          "name": "Bert Mitchell F",
          "x": 775,
          "y": 1066,
          "spriteId": 15,
          "positionKind": "authored-spawn"
        }
      ]
    }
  ]
};
