window.BRITANNIA_MAP_CONFIG = {
    imageUrl: 'images/U6GameWorld.png',
    imageSize: [4096, 4096],
    xRange: [0, 1024],
    yRange: [0, 1024],
    coordinateSystem: 'game',
    editorEnabled: false,
    levels: [
        { id: 0, name: 'Britannia Surface', imageUrl: 'images/U6GameWorld.png', worldSize: 1024 },
        { id: 1, name: 'Dungeon Level 1', imageUrl: 'images/U6GameLevel1.png', worldSize: 256 },
        { id: 2, name: 'Dungeon Level 2', imageUrl: 'images/U6GameLevel2.png', worldSize: 256 },
        { id: 3, name: 'Dungeon Level 3', imageUrl: 'images/U6GameLevel3.png', worldSize: 256 },
        { id: 4, name: 'Dungeon Level 4', imageUrl: 'images/U6GameLevel4.png', worldSize: 256 },
        { id: 5, name: 'Gargoyle Realm', imageUrl: 'images/U6GameLevel5.png', worldSize: 256 }
    ],
    markers: [
        { name: 'Britain', type: 'city', description: 'The city of Compassion; this marker identifies the town sundial.', position: { x: 0x133, y: 0x1a3 } },
        { name: "Buccaneer's Den", type: 'city', description: 'Island settlement and home of the Thieves Guild; centered among its actual saved-game residents.', position: { x: 0x233, y: 0x264 } },
        { name: 'Cove', type: 'city', description: 'Lakeside settlement near the Shrine of Compassion and the mage Rudyom.', position: { x: 0x223, y: 0x163 } },
        { name: 'Jhelom', type: 'city', description: 'The city of Valor; centered among its actual saved-game residents.', position: { x: 0x083, y: 0x36e } },
        { name: 'Minoc', type: 'city', description: 'The city of Sacrifice; this marker identifies the town sundial.', position: { x: 0x254, y: 0x063 } },
        { name: 'Moonglow', type: 'city', description: 'The city of Honesty on Verity Isle.', position: { x: 0x383, y: 0x203 } },
        { name: 'New Magincia', type: 'city', description: 'The island town associated with the virtue of Humility.', position: { x: 0x2e3, y: 0x2ab } },
        { name: 'Paws', type: 'city', description: 'Settlement south of Britain; this marker identifies the dock.', position: { x: 0x198, y: 0x264 } },
        { name: 'Skara Brae', type: 'city', description: 'The city of Spirituality; this marker identifies the town well.', position: { x: 0x054, y: 0x203 } },
        { name: 'Trinsic', type: 'city', description: 'The city of Honor; this marker identifies Brandon\'s armory.', position: { x: 0x1ad, y: 0x2e8 } },
        { name: 'Yew', type: 'city', description: 'The city of Justice; this marker identifies the town sundial.', position: { x: 0x0ec, y: 0x0a7 } },

        { name: "Lord British's Castle", type: 'castle', description: 'Castle Britannia and the throne of Lord British.', position: { x: 0x133, y: 0x15f } },
        { name: 'Empath Abbey', type: 'castle', description: 'The keep devoted to the principle of Love.', position: { x: 0x083, y: 0x0db } },
        { name: 'The Lycaeum', type: 'castle', description: 'The keep devoted to Truth, on Verity Isle.', position: { x: 0x37b, y: 0x1a4 } },
        { name: "Serpent's Hold", type: 'castle', description: 'The keep devoted to Courage, south of the mainland.', position: { x: 0x22e, y: 0x3bc } },
        { name: "Sutek's Castle", type: 'castle', description: 'The island home of Sutek, marked at the castle stairway leading to the balloon plans.', position: { x: 0x313, y: 0x3ad } },
        { name: 'Cyclops Castle', type: 'fortress', description: 'The cyclops stronghold south of Minoc.', position: { x: 0x25f, y: 0x11d } },

        { name: 'Shrine of Honesty', type: 'shrine', description: 'Virtue: Honesty. Mantra: AHM.', position: { x: 0x3a7, y: 0x109 } },
        { name: 'Shrine of Compassion', type: 'shrine', description: 'Virtue: Compassion. Mantra: MU.', position: { x: 0x1f7, y: 0x168 } },
        { name: 'Shrine of Valor', type: 'shrine', description: 'Virtue: Valor. Mantra: RA.', position: { x: 0x09f, y: 0x3b1 } },
        { name: 'Shrine of Justice', type: 'shrine', description: 'Virtue: Justice. Mantra: BEH.', position: { x: 0x127, y: 0x028 } },
        { name: 'Shrine of Sacrifice', type: 'shrine', description: 'Virtue: Sacrifice. Mantra: CAH.', position: { x: 0x33f, y: 0x0a6 } },
        { name: 'Shrine of Honor', type: 'shrine', description: 'Virtue: Honor. Mantra: SUMM.', position: { x: 0x147, y: 0x339 } },
        { name: 'Shrine of Humility', type: 'shrine', description: 'Virtue: Humility. Mantra: LUM.', position: { x: 0x397, y: 0x3a8 } },

        { name: 'Dungeon Wrong', type: 'dungeon', description: 'Surface entrance to Wrong; its depths connect with Covetous.', position: { x: 0x1f4, y: 0x053 } },
        { name: 'Dungeon Covetous', type: 'dungeon', description: 'Surface entrance to Covetous, northeast of Minoc.', position: { x: 0x273, y: 0x073 } },
        { name: 'Dungeon Destard', type: 'dungeon', description: 'Surface entrance to Destard, the dungeon containing dragon eggs.', position: { x: 0x120, y: 0x29d } },
        { name: 'Dungeon Hythloth', type: 'dungeon', description: 'Britannian entrance to Hythloth on the Isle of the Avatar.', position: { x: 0x384, y: 0x3a4 } },
        { name: 'Dungeon Shame', type: 'dungeon', description: 'Surface entrance near Lost Lake; Old Ybarra waits on the fourth level.', position: { x: 0x0eb, y: 0x19b } },
        { name: 'Ant Mound', type: 'dungeon', description: 'Entrance to the ant caves and the pirate-map fragment hidden below.', position: { x: 0x365, y: 0x0bb } },
        { name: 'Pirate Cave', type: 'dungeon', description: 'Cave entrance on the island south of New Magincia.', position: { x: 0x2c3, y: 0x342 } },
        { name: 'Heftimus Cave', type: 'dungeon', description: 'Cave entrance on the Valorian Isles.', position: { x: 0x084, y: 0x35b } },
        { name: "Buccaneer's Cave", type: 'dungeon', description: 'Surface entrance on Buccaneer\'s Isle to the connected sewer passages.', position: { x: 0x234, y: 0x253 } },

        { name: 'Shrine of the Codex', type: 'quest', description: 'The Codex of Ultimate Wisdom on the Isle of the Avatar.', position: { x: 0x39b, y: 0x354 } },
        { name: "Bonn's House", type: 'quest', description: 'Home of Bonn, who keeps a fragment of Captain Hawkins\'s map.', position: { x: 0x3a3, y: 0x0d3 } },
        { name: 'Vortex Cube', type: 'quest', description: 'The actual Vortex Cube object, located directly in the original saved-game object records.', position: { x: 0x093, y: 0x039, z: 4 } },
        { name: 'Nicodemus', type: 'quest', description: 'The magician Nicodemus, north of Britain; located from his original saved actor record.', position: { x: 0x14e, y: 0x0cb } },
        { name: 'Rudyom', type: 'quest', description: 'The magician Rudyom, northeast of Cove; located from his original saved actor record.', position: { x: 0x243, y: 0x15c } },
        { name: 'Ephemerides', type: 'quest', description: 'The lens maker near the Lycaeum; located from his original saved actor record.', position: { x: 0x3b1, y: 0x18e } },
        { name: 'Mariah', type: 'quest', description: 'Mariah at the Lycaeum; located from her original saved actor record.', position: { x: 0x376, y: 0x1bc } },

        { name: "Iolo's Hut", type: 'site', description: 'The woodland home of Iolo.', position: { x: 0x0c3, y: 0x0e8 } },
        { name: 'Xiao', type: 'site', description: 'The magician Xiao on Verity Isle; located from her original saved actor record.', position: { x: 0x360, y: 0x159 } },
        { name: 'Horance', type: 'site', description: 'The magician Horance; located from his original saved actor record.', position: { x: 0x034, y: 0x1d2 } },
        { name: 'Wisps', type: 'site', description: 'Documented wisp encounter outside Empath Abbey.', position: { x: 0x0a5, y: 0x115 } },
        { name: 'Mushroom Isle', type: 'site', description: 'The mushroom-covered island south of Paws.', position: { x: 0x19b, y: 0x29c } },
        { name: 'Isle of the Avatar Lake', type: 'site', description: 'The lake entrance on the Isle of the Avatar.', position: { x: 0x36c, y: 0x383 } },
        { name: 'Britain Gold Exchange', type: 'site', description: 'The gold exchange in Britain.', position: { x: 0x144, y: 0x18c } },

        { name: "Bonn's Basement", type: 'quest', description: 'The basement containing Bonn\'s pirate-map fragment.', position: { x: 0x0e9, y: 0x032, z: 1 } },
        { name: "Shame: Skeleton's House", type: 'dungeon', description: 'The skeleton\'s house on the first level of Shame.', position: { x: 0x02c, y: 0x05b, z: 1 } },
        { name: 'Shame: Underground River', type: 'site', description: 'Underground river with gold nuggets in Shame.', position: { x: 0x037, y: 0x093, z: 1 } },
        { name: 'Castle Britannia Sewer Entrance', type: 'dungeon', description: 'One of the Castle Britannia sewer entrances connected to Buccaneer\'s Cave.', position: { x: 0x044, y: 0x04b, z: 1 } },
        { name: 'Daros', type: 'quest', description: 'Daros in the passages beneath Castle Britannia; located from his original saved actor record.', position: { x: 0x044, y: 0x073, z: 1 } },

        { name: 'Ant Cave: Mushroom Lake', type: 'site', description: 'The mushroom lake on the second level of the ant caves.', position: { x: 0x0e4, y: 0x02b, z: 2 } },
        { name: "Buccaneer's Cave: Glass Sword and Magic Bow", type: 'quest', description: 'Documented cache containing a glass sword and a magic bow.', position: { x: 0x09c, y: 0x07e, z: 2 } },

        { name: 'Wrong and Covetous Map Room', type: 'quest', description: 'The shared map room reached through the connected Wrong and Covetous dungeons.', position: { x: 0x093, y: 0x003, z: 3 } },
        { name: 'Ant Cave: Object Stores', type: 'site', description: 'Object-storage area on the third level of the ant caves.', position: { x: 0x0ad, y: 0x015, z: 3 } },
        { name: 'Ant Cave: Hole to the Map', type: 'quest', description: 'The hole leading toward the pirate-map fragment below.', position: { x: 0x0a4, y: 0x02b, z: 3 } },
        { name: 'Shame: Magic Bow', type: 'quest', description: 'A magic bow hidden on the third level of Shame.', position: { x: 0x063, y: 0x006, z: 3 } },
        { name: "Buccaneer's Cave: Spider Cache", type: 'quest', description: 'The spider-protected cache beneath Buccaneer\'s Isle.', position: { x: 0x081, y: 0x0dd, z: 3 } },
        { name: "Buccaneer's Cave: Underground Lake Isle", type: 'site', description: 'The underground lake island south of Phoenix.', position: { x: 0x083, y: 0x08c, z: 3 } },
        { name: 'Phoenix the Thief', type: 'quest', description: 'Phoenix in the third-level passages of Buccaneer\'s Cave; located from her original saved actor record.', position: { x: 0x074, y: 0x042, z: 3 } },

        { name: "Sutek's Castle: Balloon Plans", type: 'quest', description: 'The man holding the hot-air-balloon plans in the fourth basement level.', position: { x: 0x0b4, y: 0x0dc, z: 4 } },
        { name: 'Ant Cave: Pirate Map Fragment', type: 'quest', description: 'The pirate-map fragment at the bottom of the ant caves.', position: { x: 0x0f7, y: 0x027, z: 4 } },
        { name: 'Destard: Dragon Eggs', type: 'quest', description: 'Dragon eggs on the fourth level of Destard.', position: { x: 0x02c, y: 0x02b, z: 4 } },
        { name: 'Captain Johne', type: 'quest', description: 'Captain John in the deepest reaches of Hythloth; located from his original saved actor record.', position: { x: 0x0e5, y: 0x0ef, z: 4 } },
        { name: 'Old Ybarra', type: 'quest', description: 'Old Ybarra and his pirate-map fragment on Shame\'s fourth level; located from his original saved actor record.', position: { x: 0x051, y: 0x01e, z: 4 } },
        { name: 'Pirate Cave: Treasure Room', type: 'quest', description: 'The treasure room at the bottom of the Pirate Cave.', position: { x: 0x09b, y: 0x0e4, z: 4 } },
        { name: 'Tomb of the Kings', type: 'site', description: 'The gargoyle kings\' tomb, reached on underground level four.', position: { x: 0x07f, y: 0x009, z: 4 } },

        { name: 'Hythloth: Gargoyle Entrance', type: 'dungeon', description: 'The Gargoyle-realm end of the Hythloth passage.', position: { x: 0x0dc, y: 0x0db, z: 5 } },
        { name: 'Valkadesh', type: 'quest', description: 'The gargoyle Valkadesh; located from his original saved actor record.', position: { x: 0x0cf, y: 0x0a4, z: 5 } },
        { name: 'Hall of Knowledge', type: 'site', description: 'The Gargoyle realm\'s Hall of Knowledge.', position: { x: 0x07f, y: 0x0af, z: 5 } },
        { name: 'Temple of Singularity', type: 'shrine', description: 'The Temple of Singularity in the Gargoyle realm.', position: { x: 0x07f, y: 0x037, z: 5 } },
        { name: 'Temple of Kings', type: 'site', description: 'The gargoyle Temple of Kings.', position: { x: 0x07f, y: 0x050, z: 5 } },
        { name: 'Shrine of Passion', type: 'shrine', description: 'The gargoyle shrine associated with Passion.', position: { x: 0x0bc, y: 0x02c, z: 5 } },
        { name: 'Shrine of Diligence', type: 'shrine', description: 'The gargoyle shrine associated with Diligence.', position: { x: 0x06c, y: 0x0dc, z: 5 } },
        { name: 'Shrine of Control', type: 'shrine', description: 'The gargoyle shrine associated with Control.', position: { x: 0x043, y: 0x02c, z: 5 } }
    ],
    npcs: [
        {"name": "Dupre", "type": "npc", "description": "a ruggedly handsome man, wearing a gleaming suit of armor.", "npcId": 2, "position": { "x": 0x134, "y": 0x161, "z": 0 } },
        {"name": "Shamino", "type": "npc", "description": "a quiet man, who almost seems to be a creature of the forest.", "npcId": 3, "position": { "x": 0x132, "y": 0x161, "z": 0 } },
        {"name": "Iolo", "type": "npc", "description": "your old friend Iolo.", "npcId": 4, "position": { "x": 0x133, "y": 0x162, "z": 0 } },
        {"name": "Lord British", "type": "npc", "description": "the noble ruler of Britannia.", "npcId": 5, "position": { "x": 0x133, "y": 0x15c, "z": 0 } },
        {"name": "Nystul", "type": "npc", "description": "a concerned looking mage.", "npcId": 6, "position": { "x": 0x131, "y": 0x15d, "z": 0 } },
        {"name": "Geoffrey", "type": "npc", "description": "a tall, handsome man.", "npcId": 7, "position": { "x": 0x135, "y": 0x15d, "z": 0 } },
        {"name": "Tholden", "type": "npc", "description": "a preoccupied man holding a ledger under one arm.", "npcId": 8, "position": { "x": 0x14d, "y": 0x197, "z": 0 } },
        {"name": "Sherry", "type": "npc", "description": "a cute little mouse.", "npcId": 9, "position": { "x": 0x121, "y": 0x17c, "z": 0 } },
        {"name": "Chuckles", "type": "npc", "description": "a carefree fellow in a ludicrous costume.", "npcId": 10, "position": { "x": 0x13f, "y": 0x175, "z": 0 } },
        {"name": "Kenneth", "type": "npc", "description": "a lively bard with laughter in his eyes.", "npcId": 11, "position": { "x": 0x121, "y": 0x18a, "z": 0 } },
        {"name": "Nan", "type": "npc", "description": "a nervous young bard.", "npcId": 12, "position": { "x": 0x120, "y": 0x18a, "z": 0 } },
        {"name": "Ariana", "type": "npc", "description": "a cute little girl with short hair.", "npcId": 13, "position": { "x": 0x122, "y": 0x18a, "z": 0 } },
        {"name": "Matt", "type": "npc", "description": "a gaunt fellow, with eyes that take in everything and reveal nothing.", "npcId": 14, "position": { "x": 0x181, "y": 0x194, "z": 0 } },
        {"name": "Anya", "type": "npc", "description": "a buxom woman who looks hard working, yet contented.", "npcId": 15, "position": { "x": 0x17b, "y": 0x196, "z": 0 } },
        {"name": "Gwenneth", "type": "npc", "description": "a petite woman with flowing brown hair.", "npcId": 16, "position": { "x": 0x17c, "y": 0x1ad, "z": 0 } },
        {"name": "Peyton", "type": "npc", "description": "a well-dressed man with a very even temper.", "npcId": 17, "position": { "x": 0x14a, "y": 0x1b0, "z": 0 } },
        {"name": "Max", "type": "npc", "description": "a swarthy blacksmith.", "npcId": 18, "position": { "x": 0x15c, "y": 0x17a, "z": 0 } },
        {"name": "Lazeena", "type": "npc", "description": "a sad lady with hair down to her ankles.", "npcId": 19, "position": { "x": 0x154, "y": 0x1a9, "z": 0 } },
        {"name": "Fyodor", "type": "npc", "description": "a man in a multicolored jacket. His fingers are long and graceful.", "npcId": 20, "position": { "x": 0x15c, "y": 0x187, "z": 0 } },
        {"name": "Daver", "type": "npc", "description": "a man wearing a long grey cloak.", "npcId": 21, "position": { "x": 0x167, "y": 0x18e, "z": 0 } },
        {"name": "Efram", "type": "npc", "description": "a grunting and grumbling man with a large stomach.", "npcId": 22, "position": { "x": 0x161, "y": 0x192, "z": 0 } },
        {"name": "Rufus", "type": "npc", "description": "a rough and tumble man with wild, unkempt hair.", "npcId": 23, "position": { "x": 0x10a, "y": 0x19c, "z": 0 } },
        {"name": "Nema", "type": "npc", "description": "a sleepy looking young lady.", "npcId": 24, "position": { "x": 0x106, "y": 0x18a, "z": 0 } },
        {"name": "Cullen", "type": "npc", "description": "a short, dark man, covered in white flour.", "npcId": 25, "position": { "x": 0x16f, "y": 0x17a, "z": 0 } },
        {"name": "Tiberius", "type": "npc", "description": "a rotund man in monk's robes.", "npcId": 26, "position": { "x": 0x163, "y": 0x16a, "z": 0 } },
        {"name": "Wilbur", "type": "npc", "description": "a thin, dark-haired man with a nervous smile.", "npcId": 27, "position": { "x": 0x119, "y": 0x1ab, "z": 0 } },
        {"name": "Arty", "type": "npc", "description": "a silent but good-natured man.", "npcId": 28, "position": { "x": 0x12e, "y": 0x1b4, "z": 0 } },
        {"name": "Lynn", "type": "npc", "description": "a tall, willowy woman with long blond hair.", "npcId": 29, "position": { "x": 0x172, "y": 0x188, "z": 0 } },
        {"name": "Terri", "type": "npc", "description": "a sharply dressed, very voluptuous woman.", "npcId": 30, "position": { "x": 0x14a, "y": 0x18b, "z": 0 } },
        {"name": "Kytyn", "type": "npc", "description": "a slender woman wearing a leather glove on her left hand.", "npcId": 31, "position": { "x": 0x11d, "y": 0x19a, "z": 0 } },
        {"name": "Maldric", "type": "npc", "description": "a bare chested, muscular man, his body gleaming with sweat.*", "npcId": 32, "position": { "x": 0x13c, "y": 0x161, "z": 0 } },
        {"name": "Mariah", "type": "npc", "description": "a freckled young lady with an enchanting smile.", "npcId": 33, "position": { "x": 0x376, "y": 0x1bc, "z": 0 } },
        {"name": "Thariand", "type": "npc", "description": "a busy looking man wearing a blue robe.", "npcId": 34, "position": { "x": 0x37b, "y": 0x1ab, "z": 0 } },
        {"name": "Ephemerides", "type": "npc", "description": "a solemn man, constantly dusting and polishing the items in his shop.", "npcId": 35, "position": { "x": 0x3b1, "y": 0x18e, "z": 0 } },
        {"name": "Xiao", "type": "npc", "description": "a wise, scholarly woman.", "npcId": 36, "position": { "x": 0x360, "y": 0x159, "z": 0 } },
        {"name": "Dargoth", "type": "npc", "description": "a stern, severe man in white robes.", "npcId": 37, "position": { "x": 0x37b, "y": 0x19d, "z": 0 } },
        {"name": "Rob", "type": "npc", "description": "a short, congenial fellow.", "npcId": 38, "position": { "x": 0x382, "y": 0x1fa, "z": 0 } },
        {"name": "Aganar", "type": "npc", "description": "a gentleman with an air of leadership about him.", "npcId": 39, "position": { "x": 0x37e, "y": 0x203, "z": 0 } },
        {"name": "Manrel", "type": "npc", "description": "a pipe-smoking gentleman with the symbol of the Codex @tattooed on his forehead.", "npcId": 40, "position": { "x": 0x3a5, "y": 0x219, "z": 0 } },
        {"name": "Penumbra", "type": "npc", "description": "a small, inscrutable woman, cloaked in shadows.", "npcId": 41, "position": { "x": 0x39a, "y": 0x1f6, "z": 0 } },
        {"name": "Derydlus", "type": "npc", "description": "a man who looks very amused--whether with his surroundings or himself is hard to say.", "npcId": 42, "position": { "x": 0x3a8, "y": 0x210, "z": 0 } },
        {"name": "Zellivan", "type": "npc", "description": "a man with a serpent-and-heart tabard covering his chainmail.", "npcId": 43, "position": { "x": 0x08b, "y": 0x385, "z": 0 } },
        {"name": "Nomaan", "type": "npc", "description": "a blond man with broad shoulders and a stern, unsmiling face.", "npcId": 44, "position": { "x": 0x083, "y": 0x38b, "z": 0 } },
        {"name": "Stelnar", "type": "npc", "description": "an angry-looking man wearing short swords on either hip.", "npcId": 45, "position": { "x": 0x079, "y": 0x376, "z": 0 } },
        {"name": "Van Kellian", "type": "npc", "description": "a man dressed in velvets and silks of yellow, green and blue.", "npcId": 46, "position": { "x": 0x079, "y": 0x373, "z": 0 } },
        {"name": "Heftimus", "type": "npc", "description": "a beggar, clad in the rags of a sailor, with a hook for a right hand.", "npcId": 47, "position": { "x": 0x099, "y": 0x359, "z": 0 } },
        {"name": "Lyssandra", "type": "npc", "description": "a girl of perhaps twelve years.", "npcId": 48, "position": { "x": 0x08d, "y": 0x365, "z": 0 } },
        {"name": "Culham", "type": "npc", "description": "a small man in a handsome vest made of seashells.", "npcId": 49, "position": { "x": 0x079, "y": 0x370, "z": 0 } },
        {"name": "Jerris", "type": "npc", "description": "a slender man with boots that come up to his thighs.", "npcId": 50, "position": { "x": 0x079, "y": 0x36e, "z": 0 } },
        {"name": "Arvin", "type": "npc", "description": "a tavernkeeper.", "npcId": 51, "position": { "x": 0x08b, "y": 0x366, "z": 0 } },
        {"name": "Martin", "type": "npc", "description": "a jolly, red-faced innkeeper.", "npcId": 52, "position": { "x": 0x07f, "y": 0x36a, "z": 0 } },
        {"name": "Peer", "type": "npc", "description": "a tall, muscled man with a wide grin.", "npcId": 53, "position": { "x": 0x0a0, "y": 0x36b, "z": 0 } },
        {"name": "Ben", "type": "npc", "description": "a man as large as the trees that surround his cottage.", "npcId": 54, "position": { "x": 0x0ab, "y": 0x093, "z": 0 } },
        {"name": "Le'nard", "type": "npc", "description": "a short, fat, rosy-cheeked man with long hair covering his eyes.", "npcId": 55, "position": { "x": 0x104, "y": 0x09a, "z": 0 } },
        {"name": "Andrea", "type": "npc", "description": "an enormous woman, both in size and personality.", "npcId": 56, "position": { "x": 0x0e1, "y": 0x09c, "z": 0 } },
        {"name": "Utomo", "type": "npc", "description": "a huge, dark-skined man with a close-set face.", "npcId": 57, "position": { "x": 0x103, "y": 0x0ba, "z": 0 } },
        {"name": "Nicodemus", "type": "npc", "description": "a wizened old man with a ready smile.", "npcId": 58, "position": { "x": 0x14e, "y": 0x0cb, "z": 0 } },
        {"name": "Lenora", "type": "npc", "description": "a tall, stern woman, with graying red hair and a perpetual scowl.", "npcId": 59, "position": { "x": 0x0dc, "y": 0x0a7, "z": 0 } },
        {"name": "Boskin", "type": "npc", "description": "a short, heavyset man dressed in rags.", "npcId": 60, "position": { "x": 0x0f3, "y": 0x0ba, "z": 0 } },
        {"name": "Pridgarm", "type": "npc", "description": "an old man, tall and thin. He spends all his time whittling.", "npcId": 61, "position": { "x": 0x0eb, "y": 0x0b8, "z": 0 } },
        {"name": "Jaana", "type": "npc", "description": "the druidess Jaana.", "npcId": 62, "position": { "x": 0x0ea, "y": 0x099, "z": 0 } },
        {"name": "Isabella", "type": "npc", "description": "a woman of elegant demeanor, wearing a finely embroidered dress.", "npcId": 63, "position": { "x": 0x286, "y": 0x057, "z": 0 } },
        {"name": "Selganor", "type": "npc", "description": "a slender, graceful man tuning a lute.", "npcId": 64, "position": { "x": 0x26b, "y": 0x055, "z": 0 } },
        {"name": "Tara", "type": "npc", "description": "a kindly old woman.", "npcId": 65, "position": { "x": 0x25b, "y": 0x042, "z": 0 } },
        {"name": "Gwenno", "type": "npc", "description": "a plainly dressed bard.", "npcId": 66, "position": { "x": 0x235, "y": 0x051, "z": 0 } },
        {"name": "Julia", "type": "npc", "description": "a sturdy woman with calloused hands and a loud manner.", "npcId": 67, "position": { "x": 0x27b, "y": 0x04d, "z": 0 } },
        {"name": "Michelle", "type": "npc", "description": "an industrious young woman.", "npcId": 68, "position": { "x": 0x242, "y": 0x059, "z": 0 } },
        {"name": "Aaron", "type": "npc", "description": "a plump blond man with curly blond hair and a cheerful face.", "npcId": 69, "position": { "x": 0x2a6, "y": 0x063, "z": 0 } },
        {"name": "Dale", "type": "npc", "description": "a short, barrel-chested man.", "npcId": 70, "position": { "x": 0x268, "y": 0x055, "z": 0 } },
        {"name": "James", "type": "npc", "description": "a young lad.", "npcId": 71, "position": { "x": 0x25b, "y": 0x06b, "z": 0 } },
        {"name": "Trebor", "type": "npc", "description": "a tall, muscled man with a wide grin.", "npcId": 72, "position": { "x": 0x252, "y": 0x074, "z": 0 } },
        {"name": "Troy", "type": "npc", "description": "a spidery looking man with delicate hands.", "npcId": 73, "position": { "x": 0x257, "y": 0x05e, "z": 0 } },
        {"name": "Doris", "type": "npc", "description": "a stunningly beautiful young woman.", "npcId": 74, "position": { "x": 0x23d, "y": 0x056, "z": 0 } },
        {"name": "Sandy", "type": "npc", "description": "a shifty-eyed man with a strange smile. He smells of rancid grease and cooking smoke.", "npcId": 75, "position": { "x": 0x194, "y": 0x30c, "z": 0 } },
        {"name": "Whitsaber", "type": "npc", "description": "a balding but distinguished man.", "npcId": 76, "position": { "x": 0x192, "y": 0x2e3, "z": 0 } },
        {"name": "Lawrence", "type": "npc", "description": "a small, fussy looking man.", "npcId": 77, "position": { "x": 0x1a2, "y": 0x322, "z": 0 } },
        {"name": "Harold", "type": "npc", "description": "a tall, muscular man with a solemn look on his face.", "npcId": 78, "position": { "x": 0x1a3, "y": 0x2ea, "z": 0 } },
        {"name": "Brandon", "type": "npc", "description": "a golden-haired young man.", "npcId": 79, "position": { "x": 0x1ab, "y": 0x2f0, "z": 0 } },
        {"name": "Immanuelle", "type": "npc", "description": "a sultry, dark-skinned woman dressed in riding-leathers.", "npcId": 80, "position": { "x": 0x1a3, "y": 0x319, "z": 0 } },
        {"name": "Tobatha", "type": "npc", "description": "a doddering old woman.", "npcId": 81, "position": { "x": 0x1b5, "y": 0x323, "z": 0 } },
        {"name": "Trenton", "type": "npc", "description": "a tall, rather well dressed man with a wilted smile.", "npcId": 82, "position": { "x": 0x054, "y": 0x203, "z": 0 } },
        {"name": "Gideon", "type": "npc", "description": "a man bent over with age. An old brown tunic hangs loosely on him.", "npcId": 83, "position": { "x": 0x05e, "y": 0x20a, "z": 0 } },
        {"name": "Stivius", "type": "npc", "description": "a tiny little man with wild eyes.", "npcId": 84, "position": { "x": 0x04b, "y": 0x21c, "z": 0 } },
        {"name": "Marta", "type": "npc", "description": "a rather plump woman with darting eyes.", "npcId": 85, "position": { "x": 0x065, "y": 0x20b, "z": 0 } },
        {"name": "Yorl", "type": "npc", "description": "a huge, imposing man adorned in a leather apron.", "npcId": 86, "position": { "x": 0x043, "y": 0x1ed, "z": 0 } },
        {"name": "Dezana", "type": "npc", "description": "a very large woman with a deliberate smile.", "npcId": 87, "position": { "x": 0x05b, "y": 0x1fb, "z": 0 } },
        {"name": "Horance", "type": "npc", "description": "a bent, aging man with a scraggly beard and few teeth.", "npcId": 88, "position": { "x": 0x034, "y": 0x1d2, "z": 0 } },
        {"name": "Marney", "type": "npc", "description": "a tall, delicate looking female. Her smile puts you at ease.*", "npcId": 89, "position": { "x": 0x053, "y": 0x1ec, "z": 0 } },
        {"name": "Michael", "type": "npc", "description": "a tall man with muscles looking like huge snakes.", "npcId": 90, "position": { "x": 0x0d3, "y": 0x1d2, "z": 0 } },
        {"name": "Quenton", "type": "npc", "description": "a vaporous form hovering before you.", "npcId": 91, "position": { "x": 0x04b, "y": 0x213, "z": 0 } },
        {"name": "Antonio", "type": "npc", "description": "a gentleman of slight build and refined manners.", "npcId": 92, "position": { "x": 0x2db, "y": 0x2a7, "z": 0 } },
        {"name": "William", "type": "npc", "description": "an old farmer who looks to have has made his peace with life.", "npcId": 93, "position": { "x": 0x2fb, "y": 0x290, "z": 0 } },
        {"name": "Conor", "type": "npc", "description": "a stalwart fellow, with a look of placid concentration.", "npcId": 94, "position": { "x": 0x2f3, "y": 0x2cc, "z": 0 } },
        {"name": "Charlotte", "type": "npc", "description": "a pretty young woman with downcast eyes.", "npcId": 95, "position": { "x": 0x2e1, "y": 0x29e, "z": 0 } },
        {"name": "Dunbar", "type": "npc", "description": "a plump, jovial fellow chewing on a leg of lamb.", "npcId": 96, "position": { "x": 0x2e2, "y": 0x2b5, "z": 0 } },
        {"name": "Katrina", "type": "npc", "description": "the humble peasant Katrina.", "npcId": 97, "position": { "x": 0x2fa, "y": 0x2c3, "z": 0 } },
        {"name": "Aurendir", "type": "npc", "description": "a short man dressed in shepherds clothing.", "npcId": 98, "position": { "x": 0x2eb, "y": 0x2be, "z": 0 } },
        {"name": "Patrick", "type": "npc", "description": "a colorfully garbed bard.", "npcId": 99, "position": { "x": 0x183, "y": 0x271, "z": 0 } },
        {"name": "Thindle", "type": "npc", "description": "a little, white haired man hunched over with age.", "npcId": 100, "position": { "x": 0x196, "y": 0x25c, "z": 0 } },
        {"name": "Mortude", "type": "npc", "description": "a man nearly as wide as he is tall.", "npcId": 101, "position": { "x": 0x17b, "y": 0x26b, "z": 0 } },
        {"name": "Marissa", "type": "npc", "description": "a finely adorned woman with a tight mouth and wide eyes.", "npcId": 102, "position": { "x": 0x182, "y": 0x256, "z": 0 } },
        {"name": "Arbeth", "type": "npc", "description": "a frightened little man who never looks you in the eye.", "npcId": 103, "position": { "x": 0x18d, "y": 0x26d, "z": 0 } },
        {"name": "Grison", "type": "npc", "description": "a figure covered from head to toe with flour.", "npcId": 104, "position": { "x": 0x161, "y": 0x236, "z": 0 } },
        {"name": "Dorin", "type": "npc", "description": "a plump older woman with an apron about her waist.", "npcId": 105, "position": { "x": 0x166, "y": 0x26f, "z": 0 } },
        {"name": "Merideth", "type": "npc", "description": "a little girl with a doll in her hands.", "npcId": 106, "position": { "x": 0x18d, "y": 0x249, "z": 0 } },
        {"name": "Hendle", "type": "npc", "description": "a man whose pungent smell greets you before he can.", "npcId": 107, "position": { "x": 0x17c, "y": 0x25c, "z": 0 } },
        {"name": "Ubermon", "type": "npc", "description": "a tall man with a disarming grin.", "npcId": 108, "position": { "x": 0x167, "y": 0x263, "z": 0 } },
        {"name": "Timothy", "type": "npc", "description": "a man with sea-blue eyes and a warm smile.", "npcId": 109, "position": { "x": 0x17b, "y": 0x276, "z": 0 } },
        {"name": "Dr Cat", "type": "npc", "description": "an amused looking gentleman.", "npcId": 110, "position": { "x": 0x18b, "y": 0x242, "z": 0 } },
        {"name": "Captain Fox", "type": "npc", "description": "a handsome gentleman, immaculately dressed.", "npcId": 111, "position": { "x": 0x236, "y": 0x26c, "z": 0 } },
        {"name": "Elad", "type": "npc", "description": "an uncomfortable looking man sitting behind a cup of tea.", "npcId": 112, "position": { "x": 0x232, "y": 0x26c, "z": 0 } },
        {"name": "Leodon", "type": "npc", "description": "a woman with a slightly seaworn look, but delicate hands.", "npcId": 113, "position": { "x": 0x22e, "y": 0x26c, "z": 0 } },
        {"name": "Leonna", "type": "npc", "description": "a smartly dressed woman. Her smile has a delightful subtlety to it.", "npcId": 114, "position": { "x": 0x230, "y": 0x26a, "z": 0 } },
        {"name": "Budo", "type": "npc", "description": "a chubby, jovial merchant.", "npcId": 115, "position": { "x": 0x233, "y": 0x25c, "z": 0 } },
        {"name": "Homer", "type": "npc", "description": "a shifty-eyed character. He carries a cane and walks with a slight limp.", "npcId": 116, "position": { "x": 0x23d, "y": 0x262, "z": 0 } },
        {"name": "Johann", "type": "npc", "description": "an uneasy looking bard.", "npcId": 117, "position": { "x": 0x229, "y": 0x262, "z": 0 } },
        {"name": "Shawn", "type": "npc", "description": "a charismatic man with an engaging smile.", "npcId": 118, "position": { "x": 0x233, "y": 0x263, "z": 0 } },
        {"name": "Petroph", "type": "npc", "description": "a giant of a man with a solemn stare.", "npcId": 119, "position": { "x": 0x233, "y": 0x264, "z": 0 } },
        {"name": "Enrik", "type": "npc", "description": "a scarred man with a gap-toothed grin and large, calloused hands.", "npcId": 120, "position": { "x": 0x224, "y": 0x27b, "z": 0 } },
        {"name": "Fentrissa", "type": "npc", "description": "a strong, sinewy woman with a hard look about her.", "npcId": 121, "position": { "x": 0x23d, "y": 0x27c, "z": 0 } },
        {"name": "Gilron", "type": "npc", "description": "a feverish looking warrior.", "npcId": 122, "position": { "x": 0x238, "y": 0x16c, "z": 0 } },
        {"name": "Artegal", "type": "npc", "description": "a heavily scarred man with a look of agony on his face.", "npcId": 123, "position": { "x": 0x23a, "y": 0x16c, "z": 0 } },
        {"name": "Gertan", "type": "npc", "description": "a burly man, who looks a little healthier than the other patients.", "npcId": 124, "position": { "x": 0x23c, "y": 0x16c, "z": 0 } },
        {"name": "ed", "type": "npc", "description": "an unconcious man, his face twisted with pain.", "npcId": 125, "position": { "x": 0x23e, "y": 0x16c, "z": 0 } },
        {"name": "Sasha", "type": "npc", "description": "a pretty young nurse with violet eyes.", "npcId": 126, "position": { "x": 0x23b, "y": 0x16b, "z": 0 } },
        {"name": "Ahrmaand", "type": "npc", "description": "a distinguished looking gentleman.", "npcId": 127, "position": { "x": 0x22f, "y": 0x15a, "z": 0 } },
        {"name": "Rudyom", "type": "npc", "description": "a dark, bearded man dressed in flowing white robes.", "npcId": 128, "position": { "x": 0x243, "y": 0x15c, "z": 0 } },
        {"name": "Sutek", "type": "npc", "description": "a white-haired mage in flowing robes with a mad gleam in his eye.", "npcId": 129, "position": { "x": 0x313, "y": 0x3ab, "z": 0 } },
        {"name": "Pushme Pullyu", "type": "npc", "description": "a bizarre, two-headed beast. Both heads take turns speaking to you.", "npcId": 130, "position": { "x": 0x0c3, "y": 0x0f4, "z": 2 } },
        {"name": "Gorn", "type": "npc", "description": "a burly barbarian warrior.", "npcId": 131, "position": { "x": 0x0c3, "y": 0x0ec, "z": 4 } },
        {"name": "Smith", "type": "npc", "description": "a fine looking horse.", "npcId": 132, "position": { "x": 0x0c7, "y": 0x0e8, "z": 0 } },
        {"name": "Zoltan", "type": "npc", "description": "a lively soul of a gypsy, with a bit of a wild look to him.", "npcId": 133, "position": { "x": 0x101, "y": 0x0a8, "z": 0 } },
        {"name": "Karina", "type": "npc", "description": "a gypsy girl poised on the verge of womanhood.", "npcId": 134, "position": { "x": 0x0ff, "y": 0x0a7, "z": 0 } },
        {"name": "Kador", "type": "npc", "description": "an amiable, shaggy mutt.", "npcId": 135, "position": { "x": 0x101, "y": 0x0a6, "z": 0 } },
        {"name": "Taynith", "type": "npc", "description": "a mysterious gypsy woman wearing an ankh pendant.", "npcId": 136, "position": { "x": 0x0fd, "y": 0x0a7, "z": 0 } },
        {"name": "Blaine", "type": "npc", "description": "a slightly built gypsy lad.", "npcId": 137, "position": { "x": 0x100, "y": 0x0a6, "z": 0 } },
        {"name": "Arturos", "type": "npc", "description": "a colorfully clad, bemused looking gypsy.", "npcId": 138, "position": { "x": 0x190, "y": 0x2b3, "z": 0 } },
        {"name": "Andreas", "type": "npc", "description": "a handsome, carefree gypsy man.", "npcId": 139, "position": { "x": 0x193, "y": 0x2b5, "z": 0 } },
        {"name": "Wanda", "type": "npc", "description": "a gypsy wench with a voluptuous figure.", "npcId": 140, "position": { "x": 0x192, "y": 0x2b3, "z": 0 } },
        {"name": "Sin'Vraal", "type": "npc", "description": "the daemon Sin'Vraal.", "npcId": 141, "position": { "x": 0x32a, "y": 0x0ea, "z": 0 } },
        {"name": "Bonn", "type": "npc", "description": "a short, barefooted crazy man.", "npcId": 142, "position": { "x": 0x3a9, "y": 0x0d8, "z": 0 } },
        {"name": "Papa", "type": "npc", "description": "a huge male cyclops.", "npcId": 143, "position": { "x": 0x267, "y": 0x128, "z": 0 } },
        {"name": "Mama", "type": "npc", "description": "a huge female cyclops.", "npcId": 144, "position": { "x": 0x266, "y": 0x122, "z": 0 } },
        {"name": "Myles", "type": "npc", "description": "a young human child.", "npcId": 145, "position": { "x": 0x260, "y": 0x100, "z": 0 } },
        {"name": "Glen", "type": "npc", "description": "a quiet, pale, almost motionless gentleman.", "npcId": 146, "position": { "x": 0x08b, "y": 0x0bb, "z": 0 } },
        {"name": "Sylaina", "type": "npc", "description": "a voluptuous woman dressed in dark blue velvet over white cloth.", "npcId": 147, "position": { "x": 0x044, "y": 0x0b2, "z": 0 } },
        {"name": "Stephanie", "type": "npc", "description": "a young woman who stares into the distance.", "npcId": 148, "position": { "x": 0x07a, "y": 0x0c3, "z": 0 } },
        {"name": "Faren", "type": "npc", "description": "a good looking young man with a wine glass in his hand.", "npcId": 149, "position": { "x": 0x09a, "y": 0x0d5, "z": 0 } },
        {"name": "Zeke", "type": "npc", "description": "a strong looking man with just one arm.", "npcId": 150, "position": { "x": 0x0a7, "y": 0x0db, "z": 0 } },
        {"name": "Eckhart", "type": "npc", "description": "a gnarled man with knobby muscles.", "npcId": 151, "position": { "x": 0x097, "y": 0x0e0, "z": 0 } },
        {"name": "Gherick", "type": "npc", "description": "a tall man, covered with scars and drooling uncontrollably.", "npcId": 152, "position": { "x": 0x217, "y": 0x3c3, "z": 0 } },
        {"name": "Shubin", "type": "npc", "description": "a man with a wide bottom. His voice is almost like a woman's.", "npcId": 153, "position": { "x": 0x23a, "y": 0x3b4, "z": 0 } },
        {"name": "Amanda", "type": "npc", "description": "a large black woman with a loud laugh.", "npcId": 154, "position": { "x": 0x259, "y": 0x39a, "z": 0 } },
        {"name": "Caradon", "type": "npc", "description": "a paladin with a longsword on his back.", "npcId": 155, "position": { "x": 0x209, "y": 0x3be, "z": 0 } },
        {"name": "Morchella", "type": "npc", "description": "a tough-looking woman with a walk like a troll.", "npcId": 156, "position": { "x": 0x26c, "y": 0x3b6, "z": 0 } },
        {"name": "de Hugh", "type": "npc", "description": "a commanding presence: a tall warrior in black armor.", "npcId": 157, "position": { "x": 0x209, "y": 0x3bb, "z": 0 } },
        {"name": "Loubet", "type": "npc", "description": "a tall and dashing gentleman.", "npcId": 158, "position": { "x": 0x232, "y": 0x3c5, "z": 0 } },
        {"name": "Koranada", "type": "npc", "description": "a dignified man wearing a loose jacket decorated with a serpent.", "npcId": 159, "position": { "x": 0x225, "y": 0x3af, "z": 0 } },
        {"name": "Simon", "type": "npc", "description": "a muscular knight. He speaks in a raspy voice.", "npcId": 160, "position": { "x": 0x222, "y": 0x3a2, "z": 0 } },
        {"name": "Tessa", "type": "npc", "description": "a well dressed woman.", "npcId": 161, "position": { "x": 0x224, "y": 0x3a2, "z": 0 } },
        {"name": "Seggallion", "type": "npc", "description": "a huge, muscled warrior with a sad look in his eyes.", "npcId": 162, "position": { "x": 0x20d, "y": 0x3be, "z": 0 } },
        {"name": "Finn", "type": "npc", "description": "a sly looking fellow, dressed in rags.", "npcId": 163, "position": { "x": 0x130, "y": 0x191, "z": 0 } },
        {"name": "Beh Lem", "type": "npc", "description": "a small, light-skinned gargoyle.", "npcId": 164, "position": { "x": 0x0d7, "y": 0x0de, "z": 5 } },
        {"name": "Bolesh", "type": "npc", "description": "a strong, winged gargoyle warrior. He is sorely wounded.", "npcId": 165, "position": { "x": 0x092, "y": 0x07e, "z": 5 } },
        {"name": "Caretaker", "type": "npc", "description": "an old, winged gargoyle. An odd device crafted of glass and metal rests upon his face.", "npcId": 166, "position": { "x": 0x059, "y": 0x094, "z": 5 } },
        {"name": "Draxinusom", "type": "npc", "description": "a large, winged gargoyle of regal bearing.", "npcId": 167, "position": { "x": 0x05c, "y": 0x094, "z": 5 } },
        {"name": "Naxatilor", "type": "npc", "description": "a dark, rough-skinned gargoyle.", "npcId": 168, "position": { "x": 0x08f, "y": 0x09a, "z": 5 } },
        {"name": "Valkadesh", "type": "npc", "description": "a tall, thin, winged gargoyle.", "npcId": 169, "position": { "x": 0x0cf, "y": 0x0a4, "z": 5 } },
        {"name": "Lensmaker", "type": "npc", "description": "a very old gargoyle.", "npcId": 170, "position": { "x": 0x0cc, "y": 0x064, "z": 5 } },
        {"name": "Snake Charmer", "type": "npc", "description": "an old winged gargoyle.", "npcId": 171, "position": { "x": 0x03c, "y": 0x0c4, "z": 5 } },
        {"name": "Goodscrafter", "type": "npc", "description": "a quiet, listless gargoyle.", "npcId": 172, "position": { "x": 0x05c, "y": 0x05c, "z": 5 } },
        {"name": "Healer", "type": "npc", "description": "a somber and calm gargoyle.", "npcId": 173, "position": { "x": 0x092, "y": 0x083, "z": 5 } },
        {"name": "Weaponsmith", "type": "npc", "description": "a young, nervous-looking gargoyle.", "npcId": 174, "position": { "x": 0x0ac, "y": 0x061, "z": 5 } },
        {"name": "Foodmaker", "type": "npc", "description": "a large and boisterous gargoyle.*", "npcId": 175, "position": { "x": 0x058, "y": 0x05c, "z": 5 } },
        {"name": "Farmer Nash", "type": "npc", "description": "a gaunt, tired-looking winged gargoyle.", "npcId": 176, "position": { "x": 0x061, "y": 0x055, "z": 5 } },
        {"name": "Farmer Krill", "type": "npc", "description": "a large, healthy-looking winged gargoyle.", "npcId": 177, "position": { "x": 0x0a7, "y": 0x05c, "z": 5 } },
        {"name": "Mole", "type": "npc", "description": "a coarse looking individual", "npcId": 178, "position": { "x": 0x08b, "y": 0x0c6, "z": 0 } },
        {"name": "Sionnach", "type": "npc", "description": "a troubadour with a drum. His tailored suit is travel-worn but bright.", "npcId": 179, "position": { "x": 0x063, "y": 0x0ce, "z": 0 } },
        {"name": "Mandrake", "type": "npc", "description": "a charming fellow with a peacock feather in his cap.", "npcId": 180, "position": { "x": 0x182, "y": 0x274, "z": 0 } },
        {"name": "Sinjen", "type": "npc", "description": "a long haired, raggedy man in stocks.", "npcId": 181, "position": { "x": 0x0fd, "y": 0x0a9, "z": 0 } },
        {"name": "Phoenix", "type": "npc", "description": "a graceful, silver haired woman in robes of blue.", "npcId": 182, "position": { "x": 0x074, "y": 0x042, "z": 3 } },
        {"name": "Captain John", "type": "npc", "description": "a long-haired gentleman with a scholarly demeanor.", "npcId": 183, "position": { "x": 0x0e5, "y": 0x0ef, "z": 4 } },
        {"name": "Daros", "type": "npc", "description": "a skinny, awkward looking man, wearing boots that come up past his knees.", "npcId": 184, "position": { "x": 0x044, "y": 0x073, "z": 1 } },
        {"name": "Ybarra", "type": "npc", "description": "a sunken-faced, starving man, dressed in rags.", "npcId": 185, "position": { "x": 0x051, "y": 0x01e, "z": 4 } },
        {"name": "Sentri", "type": "npc", "description": "a handsome warrior.", "npcId": 186, "position": { "x": 0x20d, "y": 0x3b7, "z": 0 } },
        {"name": "Linda", "type": "npc", "description": "a rugged looking lady farmer.", "npcId": 187, "position": { "x": 0x14d, "y": 0x143, "z": 0 } }
    ]
};
